if(NOT DEFINED SOURCE_ROOT)
    message(FATAL_ERROR "SOURCE_ROOT is required")
endif()

file(READ "${SOURCE_ROOT}/src/game/Object/Unit.h" unit_h)
file(READ "${SOURCE_ROOT}/src/game/Object/Unit.cpp" unit_cpp)
file(READ "${SOURCE_ROOT}/src/game/Object/Pet.h" pet_h)
file(READ "${SOURCE_ROOT}/src/game/Object/PetSpells.cpp" pet_cpp)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/PetHandler.cpp" handler_cpp)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" opcodes_cpp)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes_reference.h" reference_h)

set(mutation_applied FALSE)
macro(mutate var old new)
    string(FIND "${${var}}" "${old}" mutation_at)
    if(NOT mutation_at EQUAL -1)
        string(REPLACE "${old}" "${new}" ${var} "${${var}}")
        set(mutation_applied TRUE)
    endif()
endmacro()

if(MUTATION STREQUAL "reader_swap_scalars")
    mutate(unit_h "in >> parsedPosition >> parsedActionData;" "in >> parsedActionData >> parsedPosition;")
elseif(MUTATION STREQUAL "reader_mask_order")
    mutate(unit_h "ReadGuidMask<1, 0, 5, 3, 2, 7, 6, 4>" "ReadGuidMask<0, 1, 5, 3, 2, 7, 6, 4>")
elseif(MUTATION STREQUAL "reader_byte_order")
    mutate(unit_h "ReadGuidBytes<5, 6, 7, 3, 2, 1, 4, 0>" "ReadGuidBytes<6, 5, 7, 3, 2, 1, 4, 0>")
elseif(MUTATION STREQUAL "reader_drop_exact_length")
    mutate(unit_h "remaining != 9 + presentByteCount" "remaining < 9 + presentByteCount")
elseif(MUTATION STREQUAL "reader_drop_canonical_byte")
    mutate(unit_h "if (in[index] == 1)" "if (false)")
elseif(MUTATION STREQUAL "reader_drop_empty_guid")
    mutate(unit_h "parsedGuid.IsEmpty() || " "")
elseif(MUTATION STREQUAL "reader_drop_tail")
    mutate(unit_h " || in.rpos() != in.size()" "")
elseif(MUTATION STREQUAL "reader_assign_outputs_early")
    mutate(unit_h "uint32 parsedPosition = 0;" "position = 0;\n        uint32 parsedPosition = 0;")
elseif(MUTATION STREQUAL "pet_drop_zero")
    mutate(pet_cpp "if (!spellId)\n        return false;" "if (false)\n        return false;")
elseif(MUTATION STREQUAL "pet_drop_missing")
    mutate(pet_cpp "itr == m_spells.end() || " "")
elseif(MUTATION STREQUAL "pet_drop_removed")
    mutate(pet_cpp " || itr->second.state == PETSPELL_REMOVED" "")
elseif(MUTATION STREQUAL "pet_admit_arbitrary")
    mutate(pet_cpp "return itr->second.active == ACT_DISABLED || itr->second.active == ACT_ENABLED;" "return true;")
elseif(MUTATION STREQUAL "pet_nonconst")
    mutate(pet_h "CanToggleAutocast(uint32 spellId) const" "CanToggleAutocast(uint32 spellId)")
elseif(MUTATION STREQUAL "charm_drop_zero")
    mutate(unit_cpp "if (!spellId)" "if (false)")
elseif(MUTATION STREQUAL "charm_drop_found")
    mutate(unit_cpp "return found;" "return true;")
elseif(MUTATION STREQUAL "charm_first_match_only")
    mutate(unit_cpp "found = true;" "return true;")
elseif(MUTATION STREQUAL "charm_admit_arbitrary")
    mutate(unit_cpp "if (state != ACT_DISABLED && state != ACT_ENABLED)" "if (false)")
elseif(MUTATION STREQUAL "charm_nonconst")
    mutate(unit_h "CanToggleCreatureAutocast(uint32 spellId) const" "CanToggleCreatureAutocast(uint32 spellId)")
elseif(MUTATION STREQUAL "handler_restore_raw_guid")
    mutate(handler_cpp "MopCompactPackets::ReadPetSetAction(recv_data, position, actionData, petGuid)" "(recv_data >> petGuid)")
elseif(MUTATION STREQUAL "handler_restore_size_count")
    mutate(handler_cpp "uint32 position = 0;" "uint8 count = recv_data.size() == 24 ? 2 : 1;\n    uint32 position = 0;")
elseif(MUTATION STREQUAL "handler_drop_position")
    mutate(handler_cpp "if (position >= MAX_UNIT_ACTION_BAR_INDEX)" "if (false)")
elseif(MUTATION STREQUAL "handler_lookup_before_active_guid")
    mutate(handler_cpp "if (petGuid != _player->GetPetGuid() && petGuid != _player->GetCharmGuid())\n        return;\n\n    Creature* controlled" "Creature* controlled")
elseif(MUTATION STREQUAL "handler_drop_active_guid")
    mutate(handler_cpp "if (petGuid != _player->GetPetGuid() && petGuid != _player->GetCharmGuid())" "if (false)")
elseif(MUTATION STREQUAL "handler_drop_reverse_owner")
    mutate(handler_cpp " ||\n        controlled->GetCharmerOrOwnerGuid() != _player->GetObjectGuid()" "")
elseif(MUTATION STREQUAL "handler_weaken_authority_conjunction")
    mutate(handler_cpp "petGuid != _player->GetPetGuid() && petGuid != _player->GetCharmGuid()" "petGuid != _player->GetPetGuid() || petGuid != _player->GetCharmGuid()")
elseif(MUTATION STREQUAL "handler_drop_actions_disabled")
    mutate(handler_cpp "if (pet && (pet->GetModeFlags() & PET_MODE_DISABLE_ACTIONS))" "if (false)")
elseif(MUTATION STREQUAL "handler_drop_charminfo")
    mutate(handler_cpp "if (!charmInfo)" "if (false)")
elseif(MUTATION STREQUAL "handler_mask_requested_type")
    mutate(handler_cpp "uint8 const requestedType = UNIT_ACTION_BUTTON_TYPE(actionData);" "uint8 const requestedType = UNIT_ACTION_BUTTON_TYPE(actionData) & 0xC1;")
elseif(MUTATION MATCHES "^handler_accept_(clear|state01|reaction|command|arbitrary)$")
    mutate(handler_cpp "requestedType != ACT_DISABLED && requestedType != ACT_ENABLED" "false")
elseif(MUTATION STREQUAL "handler_drop_zero_spell")
    mutate(handler_cpp "!spellId || " "")
elseif(MUTATION STREQUAL "handler_drop_spell_lookup")
    mutate(handler_cpp "!spellInfo || " "")
elseif(MUTATION STREQUAL "handler_drop_owned_spell")
    mutate(handler_cpp "!controlled->HasSpell(spellId) || " "")
elseif(MUTATION STREQUAL "handler_drop_dbc_passive")
    mutate(handler_cpp " || IsPassiveSpell(spellInfo)" "")
elseif(MUTATION STREQUAL "handler_drop_slot_spell")
    mutate(handler_cpp "current->GetAction() != spellId ||\n        " "")
elseif(MUTATION STREQUAL "handler_drop_slot_type")
    mutate(handler_cpp " ||\n        (current->GetType() != ACT_DISABLED && current->GetType() != ACT_ENABLED)" "")
elseif(MUTATION STREQUAL "handler_drop_pet_capability")
    mutate(handler_cpp "pet && !pet->CanToggleAutocast(spellId)" "false")
elseif(MUTATION STREQUAL "handler_drop_charm_capability")
    mutate(handler_cpp "eligibleCharm && !charmInfo->CanToggleCreatureAutocast(spellId)" "false")
elseif(MUTATION STREQUAL "handler_add_alive_gate")
    mutate(handler_cpp "uint32 const spellId" "if (!controlled->IsAlive()) return;\n\n    uint32 const spellId")
elseif(MUTATION STREQUAL "handler_mirror_before_toggle")
    mutate(handler_cpp "bool const enabled" "charmInfo->SetActionBar(uint8(position), spellId, ActiveStates(requestedType));\n    bool const enabled")
elseif(MUTATION STREQUAL "handler_call_both_toggles")
    mutate(handler_cpp "pet->ToggleAutocast(spellId, enabled);"
        "pet->ToggleAutocast(spellId, enabled);\n    charmInfo->ToggleCreatureAutocast(spellId, enabled);")
elseif(MUTATION STREQUAL "handler_second_slot_write")
    mutate(handler_cpp "charmInfo->SetActionBar(uint8(position), spellId, ActiveStates(requestedType));" "charmInfo->SetActionBar(uint8(position), spellId, ActiveStates(requestedType));\n    charmInfo->SetActionBar(uint8(position), spellId, ActiveStates(requestedType));")
elseif(MUTATION STREQUAL "handler_add_rejection_log")
    mutate(handler_cpp "if (position >= MAX_UNIT_ACTION_BAR_INDEX)" "DETAIL_LOG(\"rejected\");\n    if (position >= MAX_UNIT_ACTION_BAR_INDEX)")
elseif(MUTATION STREQUAL "registration_wrong_status")
    mutate(opcodes_cpp "CMSG_PET_SET_ACTION, \"CMSG_PET_SET_ACTION\", STATUS_LOGGEDIN" "CMSG_PET_SET_ACTION, \"CMSG_PET_SET_ACTION\", STATUS_AUTHED")
elseif(MUTATION STREQUAL "registration_wrong_processing")
    mutate(opcodes_cpp "STATUS_LOGGEDIN, PROCESS_THREADUNSAFE, &WorldSession::HandlePetSetAction" "STATUS_LOGGEDIN, PROCESS_INPLACE, &WorldSession::HandlePetSetAction")
elseif(MUTATION STREQUAL "registration_route_06f0")
    mutate(opcodes_cpp "&WorldSession::HandlePetSetAction" "&WorldSession::HandlePetSpellAutocastOpcode")
elseif(MUTATION STREQUAL "reference_keep_dormant")
    mutate(reference_h "CMSG_PET_SET_ACTION                            0x12E9  ACTIVE" "CMSG_PET_SET_ACTION                            0x12E9  DORMANT")
endif()

if(DEFINED MUTATION AND NOT MUTATION STREQUAL "" AND NOT mutation_applied)
    return()
endif()

function(require_once source token context)
    # CMake lists use semicolons as separators. Replace them before MATCHALL so
    # one source match ending in ';' is counted as one match rather than two
    # list elements.
    string(REPLACE ";" "__MOP_SEMICOLON__" match_source "${source}")
    string(REPLACE ";" "__MOP_SEMICOLON__" match_token "${token}")
    string(REGEX MATCHALL "${match_token}" matches "${match_source}")
    list(LENGTH matches count)
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "${context}: expected once, found ${count}")
    endif()
endfunction()

function(require_absent source token context)
    string(FIND "${source}" "${token}" found)
    if(NOT found EQUAL -1)
        message(FATAL_ERROR "${context}: forbidden token present")
    endif()
endfunction()

string(FIND "${handler_cpp}" "void WorldSession::HandlePetSetAction" handler_begin)
string(FIND "${handler_cpp}" "void WorldSession::HandlePetRename" handler_end)
if(handler_begin EQUAL -1 OR handler_end LESS_EQUAL handler_begin)
    message(FATAL_ERROR "cannot isolate HandlePetSetAction")
endif()
math(EXPR handler_length "${handler_end} - ${handler_begin}")
string(SUBSTRING "${handler_cpp}" ${handler_begin} ${handler_length} handler)

string(FIND "${unit_h}" "inline bool ReadPetSetAction" reader_begin)
string(FIND "${unit_h}" "inline void ReadPetNameQuery" reader_end)
if(reader_begin EQUAL -1 OR reader_end LESS_EQUAL reader_begin)
    message(FATAL_ERROR "cannot isolate ReadPetSetAction")
endif()
math(EXPR reader_length "${reader_end} - ${reader_begin}")
string(SUBSTRING "${unit_h}" ${reader_begin} ${reader_length} pet_set_action_reader)

string(FIND "${pet_cpp}" "bool Pet::CanToggleAutocast" pet_capability_begin)
string(FIND "${pet_cpp}" "void Pet::ToggleAutocast" pet_capability_end)
if(pet_capability_begin EQUAL -1 OR pet_capability_end LESS_EQUAL pet_capability_begin)
    message(FATAL_ERROR "cannot isolate Pet::CanToggleAutocast")
endif()
math(EXPR pet_capability_length "${pet_capability_end} - ${pet_capability_begin}")
string(SUBSTRING "${pet_cpp}" ${pet_capability_begin} ${pet_capability_length} pet_capability)

string(FIND "${unit_cpp}" "bool CharmInfo::CanToggleCreatureAutocast" charm_capability_begin)
string(FIND "${unit_cpp}" "void CharmInfo::ToggleCreatureAutocast" charm_capability_end)
if(charm_capability_begin EQUAL -1 OR charm_capability_end LESS_EQUAL charm_capability_begin)
    message(FATAL_ERROR "cannot isolate CharmInfo::CanToggleCreatureAutocast")
endif()
math(EXPR charm_capability_length "${charm_capability_end} - ${charm_capability_begin}")
string(SUBSTRING "${unit_cpp}" ${charm_capability_begin} ${charm_capability_length} charm_capability)

require_once("${pet_set_action_reader}" "ReadPetSetAction[(]WorldPacket& in, uint32& position," "reader declaration")
require_once("${pet_set_action_reader}" "in >> parsedPosition >> parsedActionData;" "scalar order")
require_once("${pet_set_action_reader}" "ReadGuidMask<1, 0, 5, 3, 2, 7, 6, 4>" "mask order")
require_once("${pet_set_action_reader}" "ReadGuidBytes<5, 6, 7, 3, 2, 1, 4, 0>" "byte order")
require_once("${pet_set_action_reader}" "remaining != 9 [+] presentByteCount" "exact body length")
require_once("${pet_set_action_reader}" "if [(]in.index. == 1[)]" "canonical xor byte")
require_once("${pet_set_action_reader}" "parsedGuid[.]IsEmpty[(][)] [|][|] in[.]rpos[(][)] != in[.]size[(][)]" "empty and tail guards")
require_absent("${pet_set_action_reader}" "position = 0;\n        uint32 parsedPosition" "early output assignment")

require_once("${pet_h}" "CanToggleAutocast[(]uint32 spellId[)] const;" "const Pet capability")
require_once("${pet_capability}" "if [(]!spellId[)]" "Pet zero rejection")
require_once("${pet_capability}" "itr == m_spells[.]end[(][)] [|][|] itr->second[.]state == PETSPELL_REMOVED" "Pet membership and removal")
require_once("${pet_capability}" "itr->second[.]active == ACT_DISABLED [|][|] itr->second[.]active == ACT_ENABLED" "Pet exact states")
require_once("${unit_h}" "CanToggleCreatureAutocast[(]uint32 spellId[)] const;" "const charm capability")
require_once("${charm_capability}" "if [(]!spellId[)]" "charm zero rejection")
require_once("${charm_capability}" "bool found = false;" "charm found accumulator")
require_once("${charm_capability}" "found = true;" "charm matching-entry accumulation")
require_once("${charm_capability}" "state != ACT_DISABLED && state != ACT_ENABLED" "charm exact states")
require_once("${charm_capability}" "return found;" "charm full scan result")
require_absent("${charm_capability}" "return true;" "charm first-match shortcut")

require_once("${handler}" "MopCompactPackets::ReadPetSetAction[(]recv_data, position, actionData, petGuid[)]" "handler parser")
require_once("${handler}" "position >= MAX_UNIT_ACTION_BAR_INDEX" "position bound")
require_once("${handler}" "petGuid != _player->GetPetGuid[(][)] && petGuid != _player->GetCharmGuid[(][)]" "active control membership")
require_once("${handler}" "controlled->GetCharmerOrOwnerGuid[(][)] != _player->GetObjectGuid[(][)]" "reverse authority")
require_once("${handler}" "!pet && !eligibleCharm" "concrete classification")
require_once("${handler}" "PET_MODE_DISABLE_ACTIONS" "disabled action policy")
require_once("${handler}" "if [(]!charmInfo[)]" "CharmInfo guard")
require_once("${handler}" "uint8 const requestedType = UNIT_ACTION_BUTTON_TYPE[(]actionData[)];" "unmasked requested type")
require_once("${handler}" "!spellId [|][|] [(]requestedType != ACT_DISABLED && requestedType != ACT_ENABLED[)]" "exact requested states")
require_once("${handler}" "!spellInfo [|][|] !controlled->HasSpell[(]spellId[)] [|][|] IsPassiveSpell[(]spellInfo[)]" "spell authority")
require_once("${handler}" "current->GetAction[(][)] != spellId" "same slot spell")
require_once("${handler}" "current->GetType[(][)] != ACT_DISABLED && current->GetType[(][)] != ACT_ENABLED" "same slot type")
require_once("${handler}" "pet && !pet->CanToggleAutocast[(]spellId[)]" "Pet capability route")
require_once("${handler}" "eligibleCharm && !charmInfo->CanToggleCreatureAutocast[(]spellId[)]" "charm capability route")
require_once("${handler}" "pet->ToggleAutocast[(]spellId, enabled[)];" "Pet toggle")
require_once("${handler}" "charmInfo->ToggleCreatureAutocast[(]spellId, enabled[)];" "charm toggle")
require_once("${handler}" "else\n        charmInfo->ToggleCreatureAutocast[(]spellId, enabled[)];" "exclusive mutator routing")
require_once("${handler}" "charmInfo->SetActionBar[(]uint8[(]position[)], spellId, ActiveStates[(]requestedType[)][)];" "single slot mirror")
require_absent("${handler}" "recv_data >> petGuid" "legacy raw guid")
require_absent("${handler}" "size() == 24" "legacy two-record shape")
require_absent("${handler}" "controlled->IsAlive" "alive policy")
require_absent("${handler}" "DETAIL_LOG(\"rejected\")" "rejection logging")

string(FIND "${handler}" "pet->ToggleAutocast(spellId, enabled);" toggle_at)
string(FIND "${handler}" "charmInfo->SetActionBar(uint8(position), spellId, ActiveStates(requestedType));" mirror_at)
if(toggle_at EQUAL -1 OR mirror_at LESS_EQUAL toggle_at)
    message(FATAL_ERROR "authoritative toggle must precede slot mirror")
endif()

require_once("${opcodes_cpp}" "DefC[(]CMSG_PET_SET_ACTION, \"CMSG_PET_SET_ACTION\", STATUS_LOGGEDIN, PROCESS_THREADUNSAFE, &WorldSession::HandlePetSetAction[)];" "registration")
require_once("${reference_h}" "CMSG_PET_SET_ACTION[ ]+0x12E9  ACTIVE" "reference state")
