if(NOT DEFINED SOURCE_ROOT)
    message(FATAL_ERROR "SOURCE_ROOT is required")
endif()

file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/Spell.cpp" spell_source)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/SpellHandler.cpp" handler_source)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.h" opcode_header)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" opcode_source)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes_reference.h" reference_source)

string(FIND "${handler_source}" "void WorldSession::HandleUseItemOpcode" handler_start)
string(FIND "${handler_source}" "#define OPEN_CHEST" handler_end)
if(handler_start EQUAL -1 OR handler_end EQUAL -1 OR NOT handler_start LESS handler_end)
    message(FATAL_ERROR "missing use-item handler implementation")
endif()
math(EXPR handler_length "${handler_end} - ${handler_start}")
string(SUBSTRING "${handler_source}" ${handler_start} ${handler_length} use_item_handler_source)

string(FIND "${spell_source}" "struct UseItemMovement" reader_start)
if(reader_start EQUAL -1)
    message(FATAL_ERROR "missing use-item reader implementation")
endif()
string(SUBSTRING "${spell_source}" ${reader_start} -1 use_item_reader_source)

string(FIND "${use_item_reader_source}" "in.ReadGuidBytes<0, 5, 6, 3, 4, 2, 1>(itemGuid);" byte_start)
if(byte_start EQUAL -1)
    message(FATAL_ERROR "missing use-item byte section")
endif()
string(SUBSTRING "${use_item_reader_source}" ${byte_start} -1 use_item_byte_source)

function(require_once content needle description)
    string(FIND "${content}" "${needle}" first)
    if(first EQUAL -1)
        message(FATAL_ERROR "missing ${description}")
    endif()
    math(EXPR next "${first} + 1")
    string(SUBSTRING "${content}" ${next} -1 tail)
    string(FIND "${tail}" "${needle}" second)
    if(NOT second EQUAL -1)
        message(FATAL_ERROR "duplicate ${description}")
    endif()
endfunction()

function(require_order content first_needle second_needle description)
    string(FIND "${content}" "${first_needle}" first_position)
    string(FIND "${content}" "${second_needle}" second_position)
    if(first_position EQUAL -1 OR second_position EQUAL -1 OR
       NOT first_position LESS second_position)
        message(FATAL_ERROR "invalid ${description}")
    endif()
endfunction()

function(mutate_once variable needle replacement description)
    set(value "${${variable}}")
    require_once("${value}" "${needle}" "mutation target for ${description}")
    string(REPLACE "${needle}" "${replacement}" value "${value}")
    set(${variable} "${value}" PARENT_SCOPE)
endfunction()

if(MUTATION STREQUAL "use_item_opcode_value")
    mutate_once(opcode_header "CMSG_USE_ITEM                                = 0x1CC1," "CMSG_USE_ITEM                                = 0xFFFF," "use_item_opcode_value")
elseif(MUTATION STREQUAL "use_item_registration")
    mutate_once(opcode_source "DefC(CMSG_USE_ITEM, \"CMSG_USE_ITEM\"" "DefC(0xFFFF, \"removed CMSG_USE_ITEM\"" "use_item_registration")
elseif(MUTATION STREQUAL "use_item_reference_state")
    mutate_once(reference_source "CMSG_USE_ITEM                                  0x1CC1  ACTIVE" "CMSG_USE_ITEM                                  0x1CC1  DORMANT" "use_item_reference_state")
elseif(MUTATION STREQUAL "use_item_handler_reader_route")
    mutate_once(use_item_handler_source "MopSpellPackets::ReadUseItemRequest(recvPacket, request)" "MopSpellPackets::ReadCastSpellRequest(recvPacket, request.cast)" "use_item_handler_reader_route")
elseif(MUTATION STREQUAL "use_item_legacy_prefix")
    mutate_once(use_item_handler_source "MopSpellPackets::UseItemRequest request;" "uint8 bagIndex, slot, castCount;" "use_item_legacy_prefix")
elseif(MUTATION STREQUAL "use_item_swap_slot_bag")
    mutate_once(use_item_reader_source "in >> slot >> bagIndex;" "in >> bagIndex >> slot;" "use_item_swap_slot_bag")
elseif(MUTATION STREQUAL "use_item_header_order")
    mutate_once(use_item_reader_source "bool const itemTargetGuidIsZero = in.ReadBit();" "bool const itemTargetGuidIsZero = !in.ReadBit();" "use_item_header_order")
elseif(MUTATION STREQUAL "use_item_target_mask_width")
    mutate_once(use_item_reader_source "targetMask = in.ReadBits(20);" "targetMask = in.ReadBits(21);" "use_item_target_mask_width")
elseif(MUTATION STREQUAL "use_item_cast_flags_width_order")
    mutate_once(use_item_reader_source "castFlags = uint8(in.ReadBits(5));" "castFlags = uint8(in.ReadBits(4));" "use_item_cast_flags_width_order")
elseif(MUTATION STREQUAL "use_item_item_guid_mask_order")
    mutate_once(use_item_reader_source "in.ReadGuidMask<2, 7, 0>(itemGuid);" "in.ReadGuidMask<2, 0, 7>(itemGuid);" "use_item_item_guid_mask_order")
elseif(MUTATION STREQUAL "use_item_item_guid_split")
    mutate_once(use_item_reader_source "in.ReadGuidBytes<7>(itemGuid);" "in.ReadGuidBytes<6>(itemGuid);" "use_item_item_guid_split")
elseif(MUTATION STREQUAL "use_item_target_guid_mask_order")
    mutate_once(use_item_reader_source "in.ReadGuidMask<1, 0, 5, 3, 6, 4, 7, 2>(targetGuid);" "in.ReadGuidMask<0, 1, 5, 3, 6, 4, 7, 2>(targetGuid);" "use_item_target_guid_mask_order")
elseif(MUTATION STREQUAL "use_item_target_guid_byte_order")
    mutate_once(use_item_reader_source "in.ReadGuidBytes<1, 4, 3, 6, 2, 0, 7, 5>(targetGuid);" "in.ReadGuidBytes<4, 1, 3, 6, 2, 0, 7, 5>(targetGuid);" "use_item_target_guid_byte_order")
elseif(MUTATION STREQUAL "use_item_item_target_guid_orders")
    mutate_once(use_item_reader_source "in.ReadGuidMask<4, 5, 0, 1, 3, 7, 6, 2>(itemTargetGuid);" "in.ReadGuidMask<5, 4, 0, 1, 3, 7, 6, 2>(itemTargetGuid);" "use_item_item_target_guid_orders")
elseif(MUTATION STREQUAL "use_item_source_guid_and_xyz_order")
    mutate_once(use_item_reader_source "in.ReadGuidBytes<1, 5, 4>(sourceTransportGuid);" "in.ReadGuidBytes<5, 1, 4>(sourceTransportGuid);" "use_item_source_guid_and_xyz_order")
elseif(MUTATION STREQUAL "use_item_destination_guid_and_xyz_order")
    mutate_once(use_item_reader_source "in.ReadGuidBytes<0, 6, 1, 3>(destinationTransportGuid);" "in.ReadGuidBytes<6, 0, 1, 3>(destinationTransportGuid);" "use_item_destination_guid_and_xyz_order")
elseif(MUTATION STREQUAL "use_item_research_count_width")
    mutate_once(use_item_reader_source "uint8 const researchCount = uint8(in.ReadBits(2));" "uint8 const researchCount = uint8(in.ReadBits(3));" "use_item_research_count_width")
elseif(MUTATION STREQUAL "use_item_research_payload_order")
    mutate_once(use_item_byte_source "for (uint8 i = 0; i < researchCount; ++i)" "for (uint8 i = 1; i < researchCount; ++i)" "use_item_research_payload_order")
elseif(MUTATION STREQUAL "use_item_movement_force_width_and_bound")
    mutate_once(use_item_reader_source "movement.forceCount = in.ReadBits(22);" "movement.forceCount = in.ReadBits(21);" "use_item_movement_force_width_and_bound")
elseif(MUTATION STREQUAL "use_item_transport_guid3_mask")
    mutate_once(use_item_reader_source "in.ReadGuidBytes<6, 3>(movement.transportGuid);" "in.ReadGuidBytes<6>(movement.transportGuid);" "use_item_transport_guid3_mask")
elseif(MUTATION STREQUAL "use_item_movement_byte_order")
    mutate_once(use_item_reader_source "in.ReadGuidBytes<3, 7, 6, 1>(movement.guid);" "in.ReadGuidBytes<7, 3, 6, 1>(movement.guid);" "use_item_movement_byte_order")
elseif(MUTATION STREQUAL "use_item_tail_scalar_order")
    mutate_once(use_item_reader_source "in >> glyphIndex;" "in >> missileSpeed;" "use_item_tail_scalar_order")
elseif(MUTATION STREQUAL "use_item_target_string_bound")
    mutate_once(use_item_reader_source "if (targetStringLength > in.size() - in.rpos())" "if (false)" "use_item_target_string_bound")
elseif(MUTATION STREQUAL "use_item_exact_tail")
    mutate_once(use_item_reader_source "if (in.rpos() != in.size())" "if (false)" "use_item_exact_tail")
elseif(MUTATION STREQUAL "use_item_parse_before_binding")
    mutate_once(use_item_handler_source "Item* pItem = pUser->GetItemByPos(request.bagIndex, request.slot);" "Item* pItem = pUser->GetItemByPos(0, 0);" "use_item_parse_before_binding")
elseif(MUTATION STREQUAL "use_item_target_initialization")
    mutate_once(use_item_handler_source "if (!targets.InitializeForCastRequest(pUser, request.cast))" "if (false)" "use_item_target_initialization")
elseif(MUTATION STREQUAL "use_item_cast_item_arguments")
    mutate_once(use_item_handler_source "pUser->CastItemUseSpell(pItem, targets, request.cast.castCount, request.cast.glyphIndex);" "pUser->CastItemUseSpell(pItem, targets, request.cast.glyphIndex, request.cast.castCount);" "use_item_cast_item_arguments")
elseif(MUTATION STREQUAL "use_item_self_mover_guard")
    mutate_once(use_item_handler_source "if (!pUser->IsSelfMover())" "if (false)" "use_item_self_mover_guard")
elseif(MUTATION STREQUAL "use_item_item_guid_match")
    mutate_once(use_item_handler_source "if (pItem->GetObjectGuid() != request.itemGuid)" "if (false)" "use_item_item_guid_match")
elseif(MUTATION STREQUAL "use_item_glyph_bound")
    mutate_once(use_item_handler_source "if (request.cast.glyphIndex >= MAX_GLYPH_SLOT_INDEX)" "if (false)" "use_item_glyph_bound")
elseif(DEFINED MUTATION)
    message(FATAL_ERROR "unknown mutation: ${MUTATION}")
endif()

require_once("${opcode_header}" "CMSG_USE_ITEM                                = 0x1CC1," "use_item_opcode_value")
require_once("${opcode_source}" "DefC(CMSG_USE_ITEM, \"CMSG_USE_ITEM\", STATUS_LOGGEDIN, PROCESS_THREADUNSAFE, &WorldSession::HandleUseItemOpcode);" "use_item_registration")
require_once("${reference_source}" "CMSG_USE_ITEM                                  0x1CC1  ACTIVE" "use_item_reference_state")
require_once("${use_item_handler_source}" "MopSpellPackets::ReadUseItemRequest(recvPacket, request)" "use_item_handler_reader_route")
require_once("${use_item_handler_source}" "MopSpellPackets::UseItemRequest request;" "use_item_legacy_prefix")
require_once("${use_item_reader_source}" "in >> slot >> bagIndex;" "use_item_swap_slot_bag")
require_once("${use_item_reader_source}" "bool const itemTargetGuidIsZero = in.ReadBit();" "use_item_header_order")
require_once("${use_item_reader_source}" "targetMask = in.ReadBits(20);" "use_item_target_mask_width")
require_once("${use_item_reader_source}" "castFlags = uint8(in.ReadBits(5));" "use_item_cast_flags_width_order")
require_once("${use_item_reader_source}" "in.ReadGuidMask<2, 7, 0>(itemGuid);" "use_item_item_guid_mask_order")
require_once("${use_item_reader_source}" "in.ReadGuidBytes<0, 5, 6, 3, 4, 2, 1>(itemGuid);" "use_item_item_guid_split prefix")
require_once("${use_item_reader_source}" "in.ReadGuidBytes<7>(itemGuid);" "use_item_item_guid_split suffix")
require_once("${use_item_reader_source}" "in.ReadGuidMask<1, 0, 5, 3, 6, 4, 7, 2>(targetGuid);" "use_item_target_guid_mask_order")
require_once("${use_item_reader_source}" "in.ReadGuidBytes<1, 4, 3, 6, 2, 0, 7, 5>(targetGuid);" "use_item_target_guid_byte_order")
require_once("${use_item_reader_source}" "in.ReadGuidMask<4, 5, 0, 1, 3, 7, 6, 2>(itemTargetGuid);" "use_item_item_target_guid_orders mask")
require_once("${use_item_reader_source}" "in.ReadGuidBytes<6, 7, 2, 0, 3, 4, 1, 5>(itemTargetGuid);" "use_item_item_target_guid_orders bytes")
require_once("${use_item_reader_source}" "in.ReadGuidMask<3, 1, 7, 4, 2, 0, 6, 5>(sourceTransportGuid);" "use_item_source_guid_and_xyz_order mask")
require_once("${use_item_reader_source}" "in.ReadGuidBytes<1, 5, 4>(sourceTransportGuid);" "use_item_source_guid_and_xyz_order bytes")
require_order("${use_item_reader_source}" "in >> sourceX;" "in >> sourceZ;" "use_item_source_guid_and_xyz_order X-Z")
require_order("${use_item_reader_source}" "in >> sourceZ;" "in >> sourceY;" "use_item_source_guid_and_xyz_order Z-Y")
require_once("${use_item_reader_source}" "in.ReadGuidMask<2, 4, 1, 7, 6, 0, 3, 5>(destinationTransportGuid);" "use_item_destination_guid_and_xyz_order mask")
require_once("${use_item_reader_source}" "in.ReadGuidBytes<0, 6, 1, 3>(destinationTransportGuid);" "use_item_destination_guid_and_xyz_order bytes")
require_order("${use_item_reader_source}" "in >> destinationX;" "in >> destinationY;" "use_item_destination_guid_and_xyz_order X-Y")
require_order("${use_item_reader_source}" "in >> destinationY;" "in >> destinationZ;" "use_item_destination_guid_and_xyz_order Y-Z")
require_once("${use_item_reader_source}" "uint8 const researchCount = uint8(in.ReadBits(2));" "use_item_research_count_width")
require_once("${use_item_byte_source}" "for (uint8 i = 0; i < researchCount; ++i)" "use_item_research_payload_order")
require_order("${use_item_byte_source}" "in.ReadGuidBytes<0, 5, 6, 3, 4, 2, 1>(itemGuid);" "in.ReadGuidBytes<7>(itemGuid);" "use_item_research_payload_order")
require_once("${use_item_reader_source}" "movement.forceCount = in.ReadBits(22);" "use_item_movement_force_width_and_bound width")
require_once("${use_item_reader_source}" "if (movement.forceCount > (in.size() - in.rpos()) / sizeof(uint32))" "use_item_movement_force_width_and_bound bound")
require_once("${use_item_reader_source}" "in.ReadGuidBytes<6, 3>(movement.transportGuid);" "use_item_transport_guid3_mask")
require_once("${use_item_reader_source}" "in.ReadGuidBytes<3, 7, 6, 1>(movement.guid);" "use_item_movement_byte_order")
require_order("${use_item_reader_source}" "if (hasElevation)" "if (hasGlyphIndex)" "use_item_tail_scalar_order elevation-glyph")
require_order("${use_item_reader_source}" "if (hasGlyphIndex)" "if (hasMissileSpeed)" "use_item_tail_scalar_order glyph-speed")
require_order("${use_item_reader_source}" "if (hasMissileSpeed)" "if (hasCastCount)" "use_item_tail_scalar_order speed-count")
require_once("${use_item_reader_source}" "in >> glyphIndex;" "use_item_tail_scalar_order")
require_once("${use_item_reader_source}" "if (targetStringLength > in.size() - in.rpos())" "use_item_target_string_bound")
require_once("${use_item_reader_source}" "if (in.rpos() != in.size())" "use_item_exact_tail")
require_once("${use_item_handler_source}" "Item* pItem = pUser->GetItemByPos(request.bagIndex, request.slot);" "use_item_parse_before_binding")
require_once("${use_item_handler_source}" "if (!targets.InitializeForCastRequest(pUser, request.cast))" "use_item_target_initialization")
require_once("${use_item_handler_source}" "pUser->CastItemUseSpell(pItem, targets, request.cast.castCount, request.cast.glyphIndex);" "use_item_cast_item_arguments")
require_order("${use_item_handler_source}" "MopSpellPackets::ReadUseItemRequest(recvPacket, request)" "if (!targets.InitializeForCastRequest(pUser, request.cast))" "use_item_target_initialization reader order")
require_order("${use_item_handler_source}" "if (!targets.InitializeForCastRequest(pUser, request.cast))" "Item* pItem = pUser->GetItemByPos(request.bagIndex, request.slot);" "use_item_target_initialization binding order")
require_once("${use_item_handler_source}" "if (!pUser->IsSelfMover())" "use_item_self_mover_guard")
require_once("${use_item_handler_source}" "if (pItem->GetObjectGuid() != request.itemGuid)" "use_item_item_guid_match")
require_once("${use_item_handler_source}" "if (request.cast.glyphIndex >= MAX_GLYPH_SLOT_INDEX)" "use_item_glyph_bound")

foreach(legacy IN ITEMS "recvPacket >> bagIndex" "targets.ReadForCaster" "targets.ReadAdditionalData")
    string(FIND "${use_item_handler_source}" "${legacy}" position)
    if(NOT position EQUAL -1)
        message(FATAL_ERROR "legacy use-item reader remains: ${legacy}")
    endif()
endforeach()

string(FIND "${use_item_handler_source}" "MopSpellPackets::ReadUseItemRequest(recvPacket, request)" reader_position)
string(FIND "${use_item_handler_source}" "pUser->GetItemByPos(request.bagIndex, request.slot)" item_position)
if(reader_position EQUAL -1 OR item_position EQUAL -1 OR NOT reader_position LESS item_position)
    message(FATAL_ERROR "use_item_parse_before_binding")
endif()
