# SPDX-License-Identifier: GPL-3.0-or-later

if(NOT DEFINED SOURCE_ROOT)
    message(FATAL_ERROR "SOURCE_ROOT is required")
endif()

file(READ "${SOURCE_ROOT}/src/game/Object/Player.h" PLAYER_H)
file(READ "${SOURCE_ROOT}/src/game/Object/PlayerTaxi.h" PLAYER_TAXI_H)
file(READ "${SOURCE_ROOT}/src/game/Object/PlayerTaxi.cpp" PLAYER_TAXI_CPP)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/TaxiHandler.cpp" TAXI_HANDLER)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" OPCODES_CPP)
file(READ "${SOURCE_ROOT}/src/game/Server/WorldSession.cpp" WORLD_SESSION_CPP)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes_reference.h" OPCODES_REFERENCE_H)

if(DEFINED MUTATION)
    if(MUTATION STREQUAL "request_mask")
        string(REPLACE "ReadGuidMask<7, 1, 0, 4, 2, 5, 6, 3>" "ReadGuidMask<1, 7, 0, 4, 2, 5, 6, 3>" PLAYER_H "${PLAYER_H}")
    elseif(MUTATION STREQUAL "request_bytes")
        string(REPLACE "ReadGuidBytes<0, 3, 7, 5, 2, 6, 4, 1>" "ReadGuidBytes<3, 0, 7, 5, 2, 6, 4, 1>" PLAYER_H "${PLAYER_H}")
    elseif(MUTATION STREQUAL "request_xor")
        string(REPLACE "ReadGuidBytes<0, 3, 7, 5, 2, 6, 4, 1>" "ReadGuidBytesRaw<0, 3, 7, 5, 2, 6, 4, 1>" PLAYER_H "${PLAYER_H}")
    elseif(MUTATION STREQUAL "request_eof")
        string(REPLACE "if (in.rpos() != in.size())" "if (false)" PLAYER_H "${PLAYER_H}")
    elseif(MUTATION STREQUAL "reply_menu_bit")
        string(REPLACE "out.WriteBit(true);" "out.WriteBit(false);" PLAYER_H "${PLAYER_H}")
    elseif(MUTATION STREQUAL "reply_mask")
        string(REPLACE "WriteGuidMask<3, 0, 4, 2, 1, 7, 6, 5>" "WriteGuidMask<0, 3, 4, 2, 1, 7, 6, 5>" PLAYER_H "${PLAYER_H}")
    elseif(MUTATION STREQUAL "reply_count_width")
        string(REPLACE "out.WriteBits(uint32(maskSize), 24);" "out << uint32(maskSize);" PLAYER_H "${PLAYER_H}")
    elseif(MUTATION STREQUAL "reply_flush")
        string(REPLACE "out.FlushBits();" "" PLAYER_H "${PLAYER_H}")
    elseif(MUTATION STREQUAL "reply_prefix_bytes")
        string(REPLACE "WriteGuidBytes<0, 3>" "WriteGuidBytes<3, 0>" PLAYER_H "${PLAYER_H}")
    elseif(MUTATION STREQUAL "reply_suffix_bytes")
        string(REPLACE "WriteGuidBytes<5, 2, 6, 1, 7, 4>" "WriteGuidBytes<2, 5, 6, 1, 7, 4>" PLAYER_H "${PLAYER_H}")
    elseif(MUTATION STREQUAL "reply_xor")
        string(REPLACE "WriteGuidBytes<0, 3>" "WriteGuidBytesRaw<0, 3>" PLAYER_H "${PLAYER_H}")
    elseif(MUTATION STREQUAL "reply_raw_tail")
        string(REPLACE "out.append(mask, maskSize);" "" PLAYER_H "${PLAYER_H}")
    elseif(MUTATION STREQUAL "handler_parser")
        string(REPLACE "MopTaxiPackets::ParseTaxiQueryAvailableNodes(recv_data, guid)" "true" TAXI_HANDLER "${TAXI_HANDLER}")
    elseif(MUTATION STREQUAL "handler_zero_guid")
        string(REPLACE " || guid.IsEmpty()" "" TAXI_HANDLER "${TAXI_HANDLER}")
    elseif(MUTATION STREQUAL "npc_authority")
        string(REPLACE "GetNPCIfCanInteractWith(guid, UNIT_NPC_FLAG_FLIGHTMASTER)" "GetNPCIfCanInteractWith(guid, UNIT_NPC_FLAG_VENDOR)" TAXI_HANDLER "${TAXI_HANDLER}")
    elseif(MUTATION STREQUAL "interaction_before_parse")
        string(REPLACE "if (!MopTaxiPackets::ParseTaxiQueryAvailableNodes(recv_data, guid) || guid.IsEmpty())"
            "GetPlayer()->GetNPCIfCanInteractWith(guid, UNIT_NPC_FLAG_FLIGHTMASTER);\n    if (!MopTaxiPackets::ParseTaxiQueryAvailableNodes(recv_data, guid) || guid.IsEmpty())"
            TAXI_HANDLER "${TAXI_HANDLER}")
    elseif(MUTATION STREQUAL "feign_death_branch")
        string(REPLACE "if (GetPlayer()->hasUnitState(UNIT_STAT_DIED))" "if (false)" TAXI_HANDLER "${TAXI_HANDLER}")
    elseif(MUTATION STREQUAL "learn_branch")
        string(REPLACE "if (SendLearnNewTaxiNode(unit))" "if (false)" TAXI_HANDLER "${TAXI_HANDLER}")
    elseif(MUTATION STREQUAL "known_menu_branch")
        string(REPLACE "SendTaxiMenu(unit);" "" TAXI_HANDLER "${TAXI_HANDLER}")
    elseif(MUTATION STREQUAL "menu_builder")
        string(REPLACE "MopTaxiPackets::BuildShowTaxiNodes" "MopTaxiPackets::BuildStatusBody" TAXI_HANDLER "${TAXI_HANDLER}")
    elseif(MUTATION STREQUAL "menu_legacy_append")
        string(REPLACE "GetTaxiMask(GetPlayer()->IsTaxiCheater())" "AppendTaximaskTo(data, GetPlayer()->IsTaxiCheater())" TAXI_HANDLER "${TAXI_HANDLER}")
    elseif(MUTATION STREQUAL "new_path_body")
        string(REPLACE "WorldPacket msg(SMSG_NEW_TAXI_PATH, 0);" "WorldPacket msg(SMSG_NEW_TAXI_PATH, 4); msg << uint32(1);" TAXI_HANDLER "${TAXI_HANDLER}")
    elseif(MUTATION STREQUAL "request_registration")
        string(REPLACE "DefC(CMSG_TAXIQUERYAVAILABLENODES" "DefX(CMSG_TAXIQUERYAVAILABLENODES" OPCODES_CPP "${OPCODES_CPP}")
    elseif(MUTATION STREQUAL "menu_registration")
        string(REPLACE "DefS(SMSG_SHOWTAXINODES" "DefX(SMSG_SHOWTAXINODES" OPCODES_CPP "${OPCODES_CPP}")
    elseif(MUTATION STREQUAL "new_path_registration")
        string(REPLACE "DefS(SMSG_NEW_TAXI_PATH" "DefX(SMSG_NEW_TAXI_PATH" OPCODES_CPP "${OPCODES_CPP}")
    elseif(MUTATION STREQUAL "menu_admission")
        string(REPLACE "case SMSG_SHOWTAXINODES:" "case SMSG_SHOWTAXINODES_MUTATED:" WORLD_SESSION_CPP "${WORLD_SESSION_CPP}")
    elseif(MUTATION STREQUAL "new_path_admission")
        string(REPLACE "case SMSG_NEW_TAXI_PATH:" "case SMSG_NEW_TAXI_PATH_MUTATED:" WORLD_SESSION_CPP "${WORLD_SESSION_CPP}")
    elseif(MUTATION STREQUAL "request_reference")
        string(REPLACE "CMSG_TAXIQUERYAVAILABLENODES                   0x02E3  ACTIVE" "CMSG_TAXIQUERYAVAILABLENODES                   0x02E3  DORMANT" OPCODES_REFERENCE_H "${OPCODES_REFERENCE_H}")
    elseif(MUTATION STREQUAL "menu_reference")
        string(REPLACE "SMSG_SHOWTAXINODES                             0x1E1A  ACTIVE" "SMSG_SHOWTAXINODES                             0x1E1A  DORMANT" OPCODES_REFERENCE_H "${OPCODES_REFERENCE_H}")
    elseif(MUTATION STREQUAL "new_path_reference")
        string(REPLACE "SMSG_NEW_TAXI_PATH                             0x141B  ACTIVE" "SMSG_NEW_TAXI_PATH                             0x141B  DORMANT" OPCODES_REFERENCE_H "${OPCODES_REFERENCE_H}")
    elseif(MUTATION STREQUAL "mask_accessor")
        string(REPLACE "uint8 const* PlayerTaxi::GetTaxiMask" "uint8 const* PlayerTaxi::GetTaxiMaskMutated" PLAYER_TAXI_CPP "${PLAYER_TAXI_CPP}")
    elseif(MUTATION STREQUAL "mask_size_accessor")
        string(REPLACE "size_t PlayerTaxi::GetTaxiMaskSize" "size_t PlayerTaxi::GetTaxiMaskSizeMutated" PLAYER_TAXI_CPP "${PLAYER_TAXI_CPP}")
    elseif(MUTATION STREQUAL "neighbor_registration")
        string(APPEND OPCODES_CPP "\nDefC(CMSG_ACTIVATETAXIEXPRESS, accidental_neighbor);\n")
    else()
        message(FATAL_ERROR "Unknown mutation: ${MUTATION}")
    endif()
endif()

function(require_text HAYSTACK NEEDLE LABEL)
    string(FIND "${${HAYSTACK}}" "${NEEDLE}" POSITION)
    if(POSITION EQUAL -1)
        message(FATAL_ERROR "Missing ${LABEL}")
    endif()
endfunction()

string(FIND "${TAXI_HANDLER}" "void WorldSession::HandleTaxiQueryAvailableNodes" QUERY_BEGIN)
string(FIND "${TAXI_HANDLER}" "void WorldSession::SendTaxiMenu" QUERY_END)
string(FIND "${TAXI_HANDLER}" "bool WorldSession::SendLearnNewTaxiNode" LEARN_BEGIN)
string(FIND "${TAXI_HANDLER}" "void WorldSession::SendActivateTaxiReply" LEARN_END)
string(FIND "${TAXI_HANDLER}" "bool WorldSession::SendDoFlight" MENU_END)
if(QUERY_BEGIN EQUAL -1 OR QUERY_END EQUAL -1 OR LEARN_BEGIN EQUAL -1 OR
    LEARN_END EQUAL -1 OR MENU_END EQUAL -1)
    message(FATAL_ERROR "Unable to isolate taxi menu handlers")
endif()
math(EXPR QUERY_LENGTH "${QUERY_END} - ${QUERY_BEGIN}")
math(EXPR MENU_LENGTH "${MENU_END} - ${QUERY_END}")
math(EXPR LEARN_LENGTH "${LEARN_END} - ${LEARN_BEGIN}")
string(SUBSTRING "${TAXI_HANDLER}" ${QUERY_BEGIN} ${QUERY_LENGTH} QUERY_HANDLER)
string(SUBSTRING "${TAXI_HANDLER}" ${QUERY_END} ${MENU_LENGTH} MENU_HANDLER)
string(SUBSTRING "${TAXI_HANDLER}" ${LEARN_BEGIN} ${LEARN_LENGTH} LEARN_HANDLER)

require_text(PLAYER_H "ReadGuidMask<7, 1, 0, 4, 2, 5, 6, 3>" "request GUID mask order")
require_text(PLAYER_H "ReadGuidBytes<0, 3, 7, 5, 2, 6, 4, 1>" "request GUID byte order")
require_text(PLAYER_H "if (in.rpos() != in.size())" "request EOF guard")
require_text(PLAYER_H "out.WriteBit(true);" "menu bit")
require_text(PLAYER_H "WriteGuidMask<3, 0, 4, 2, 1, 7, 6, 5>" "reply GUID mask order")
require_text(PLAYER_H "out.WriteBits(uint32(maskSize), 24);" "24-bit tail count")
require_text(PLAYER_H "out.FlushBits();" "reply bit flush")
require_text(PLAYER_H "WriteGuidBytes<0, 3>" "reply prefix GUID bytes")
require_text(PLAYER_H "out << currentNode;" "reply current node")
require_text(PLAYER_H "WriteGuidBytes<5, 2, 6, 1, 7, 4>" "reply suffix GUID bytes")
require_text(PLAYER_H "out.append(mask, maskSize);" "raw mask tail")
require_text(PLAYER_TAXI_CPP "uint8 const* PlayerTaxi::GetTaxiMask(bool all) const" "mask accessor implementation")
require_text(PLAYER_TAXI_CPP "size_t PlayerTaxi::GetTaxiMaskSize() const" "mask size accessor implementation")
require_text(QUERY_HANDLER "MopTaxiPackets::ParseTaxiQueryAvailableNodes(recv_data, guid) || guid.IsEmpty()" "handler parse and zero guard")
require_text(QUERY_HANDLER "GetNPCIfCanInteractWith(guid, UNIT_NPC_FLAG_FLIGHTMASTER)" "flight-master authority")
require_text(QUERY_HANDLER "if (GetPlayer()->hasUnitState(UNIT_STAT_DIED))" "feign-death cleanup branch")
require_text(QUERY_HANDLER "if (SendLearnNewTaxiNode(unit))" "new-node learning branch")
require_text(QUERY_HANDLER "SendTaxiMenu(unit);" "known-node menu branch")
require_text(MENU_HANDLER "MopTaxiPackets::BuildShowTaxiNodes" "menu builder integration")
require_text(MENU_HANDLER "GetTaxiMask(GetPlayer()->IsTaxiCheater())" "raw mask accessor integration")
require_text(LEARN_HANDLER "WorldPacket msg(SMSG_NEW_TAXI_PATH, 0);" "empty new-path body")
require_text(OPCODES_CPP "DefC(CMSG_TAXIQUERYAVAILABLENODES" "request registration")
require_text(OPCODES_CPP "DefS(SMSG_SHOWTAXINODES" "menu registration")
require_text(OPCODES_CPP "DefS(SMSG_NEW_TAXI_PATH" "new-path registration")
require_text(WORLD_SESSION_CPP "case SMSG_SHOWTAXINODES:" "menu admission")
require_text(WORLD_SESSION_CPP "case SMSG_NEW_TAXI_PATH:" "new-path admission")
require_text(OPCODES_REFERENCE_H "SMSG_SHOWTAXINODES                             0x1E1A  ACTIVE" "menu active reference")
require_text(OPCODES_REFERENCE_H "SMSG_NEW_TAXI_PATH                             0x141B  ACTIVE" "new-path active reference")
require_text(OPCODES_REFERENCE_H "CMSG_TAXIQUERYAVAILABLENODES                   0x02E3  ACTIVE" "request active reference")

string(FIND "${QUERY_HANDLER}" "MopTaxiPackets::ParseTaxiQueryAvailableNodes(recv_data, guid)" PARSE_POSITION)
string(FIND "${QUERY_HANDLER}" "GetPlayer()->GetNPCIfCanInteractWith(guid, UNIT_NPC_FLAG_FLIGHTMASTER)" INTERACTION_POSITION)
if(PARSE_POSITION EQUAL -1 OR INTERACTION_POSITION EQUAL -1 OR NOT PARSE_POSITION LESS INTERACTION_POSITION)
    message(FATAL_ERROR "Taxi query must parse before NPC interaction")
endif()

foreach(FORBIDDEN_QUERY IN ITEMS "recv_data >> guid" "recv_data.readPackGUID")
    string(FIND "${QUERY_HANDLER}" "${FORBIDDEN_QUERY}" FORBIDDEN_QUERY_POSITION)
    if(NOT FORBIDDEN_QUERY_POSITION EQUAL -1)
        message(FATAL_ERROR "Legacy taxi-query GUID parser remains: ${FORBIDDEN_QUERY}")
    endif()
endforeach()

string(FIND "${MENU_HANDLER}" "AppendTaximaskTo" LEGACY_MASK_APPEND)
if(NOT LEGACY_MASK_APPEND EQUAL -1)
    message(FATAL_ERROR "Taxi menu must append the raw mask without the legacy length prefix")
endif()

foreach(FORBIDDEN IN ITEMS CMSG_ACTIVATETAXIEXPRESS CMSG_MOVE_SPLINE_DONE)
    string(FIND "${OPCODES_CPP}" "DefC(${FORBIDDEN}," FORBIDDEN_POSITION)
    if(NOT FORBIDDEN_POSITION EQUAL -1)
        message(FATAL_ERROR "Unexpected neighboring taxi registration: ${FORBIDDEN}")
    endif()
endforeach()

message(STATUS "MoP taxi-menu source checks passed")
