file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/SpellPackets.cpp" spell_packets)
file(READ "${SOURCE_ROOT}/src/game/Object/Unit.cpp" unit_cpp)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" opcodes_cpp)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.h" opcodes_h)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes_reference.h" opcode_reference)
file(READ "${SOURCE_ROOT}/src/game/Server/WorldSession.cpp" world_session)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/SpellEffectSkillEnchantPet.cpp" dispel_effect)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/SpellEffectTail.cpp" steal_effect)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/SpellEffectObjectCombat.cpp" interrupt_effect)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/SpellEffectDamageTeleport.cpp" instakill_effect)
file(READ "${SOURCE_ROOT}/src/game/Object/UnitMeleeDamage.cpp" melee_damage_cpp)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/Spell.h" spell_h)

if(MUTATION STREQUAL "instakill_builder")
    string(REPLACE "inline void BuildSpellInstakillLog" "inline void RemovedSpellInstakillLog" spell_h "${spell_h}")
elseif(MUTATION STREQUAL "instakill_sender")
    string(REPLACE "MopCombatLogPackets::BuildSpellInstakillLog(data, log);" "/* removed instakill serializer */" instakill_effect "${instakill_effect}")
elseif(MUTATION STREQUAL "instakill_registration")
    string(REPLACE "DefS(SMSG_SPELLINSTAKILLLOG, \"SMSG_SPELLINSTAKILLLOG\");" "/* removed instakill registration */" opcodes_cpp "${opcodes_cpp}")
elseif(MUTATION STREQUAL "instakill_gate")
    string(REPLACE "case SMSG_SPELLINSTAKILLLOG:" "case SMSG_UNKNOWN_0:" world_session "${world_session}")
elseif(MUTATION STREQUAL "instakill_reference")
    string(REPLACE "SMSG_SPELLINSTAKILLLOG                         0x09F8  ACTIVE" "SMSG_SPELLINSTAKILLLOG                         0x09F8  DORMANT" opcode_reference "${opcode_reference}")
elseif(MUTATION STREQUAL "energize_builder")
    string(REPLACE "inline void BuildSpellEnergizeLog" "inline void RemovedSpellEnergizeLog" spell_h "${spell_h}")
elseif(MUTATION STREQUAL "energize_sender")
    string(REPLACE "MopCombatLogPackets::BuildSpellEnergizeLog(data, log);" "/* removed energize serializer */" unit_cpp "${unit_cpp}")
elseif(MUTATION STREQUAL "energize_registration")
    string(REPLACE "DefS(SMSG_SPELLENERGIZELOG, \"SMSG_SPELLENERGIZELOG\");" "/* removed energize registration */" opcodes_cpp "${opcodes_cpp}")
elseif(MUTATION STREQUAL "energize_gate")
    string(REPLACE "case SMSG_SPELLENERGIZELOG:" "case SMSG_UNKNOWN_0:" world_session "${world_session}")
elseif(MUTATION STREQUAL "energize_reference")
    string(REPLACE "SMSG_SPELLENERGIZELOG                          0x0D79  ACTIVE" "SMSG_SPELLENERGIZELOG                          0x0D79  DORMANT" opcode_reference "${opcode_reference}")
elseif(MUTATION STREQUAL "heal_builder")
    string(REPLACE "inline void BuildSpellHealLog" "inline void RemovedSpellHealLog" spell_h "${spell_h}")
elseif(MUTATION STREQUAL "heal_sender")
    string(REPLACE "MopCombatLogPackets::BuildSpellHealLog(data, log);" "/* removed heal serializer */" unit_cpp "${unit_cpp}")
elseif(MUTATION STREQUAL "heal_registration")
    string(REPLACE "DefS(SMSG_SPELLHEALLOG, \"SMSG_SPELLHEALLOG\");" "/* removed heal registration */" opcodes_cpp "${opcodes_cpp}")
elseif(MUTATION STREQUAL "heal_gate")
    string(REPLACE "case SMSG_SPELLHEALLOG:" "case SMSG_UNKNOWN_0:" world_session "${world_session}")
elseif(MUTATION STREQUAL "heal_reference")
    string(REPLACE "SMSG_SPELLHEALLOG                              0x09FB  ACTIVE" "SMSG_SPELLHEALLOG                              0x09FB  DORMANT" opcode_reference "${opcode_reference}")
elseif(MUTATION STREQUAL "damage_shield_builder")
    string(REPLACE "inline void BuildSpellDamageShieldLog" "inline void RemovedSpellDamageShieldLog" spell_h "${spell_h}")
elseif(MUTATION STREQUAL "damage_shield_sender")
    string(REPLACE "MopCombatLogPackets::BuildSpellDamageShieldLog(data, log);" "/* removed damage-shield serializer */" melee_damage_cpp "${melee_damage_cpp}")
elseif(MUTATION STREQUAL "damage_shield_registration")
    string(REPLACE "DefS(SMSG_SPELLDAMAGESHIELD, \"SMSG_SPELLDAMAGESHIELD\");" "/* removed damage-shield registration */" opcodes_cpp "${opcodes_cpp}")
elseif(MUTATION STREQUAL "damage_shield_gate")
    string(REPLACE "case SMSG_SPELLDAMAGESHIELD:" "case SMSG_UNKNOWN_0:" world_session "${world_session}")
elseif(MUTATION STREQUAL "damage_shield_reference")
    string(REPLACE "SMSG_SPELLDAMAGESHIELD                         0x05F3  ACTIVE" "SMSG_SPELLDAMAGESHIELD                         0x05F3  DORMANT" opcode_reference "${opcode_reference}")
elseif(MUTATION STREQUAL "spell_miss_builder")
    string(REPLACE "inline bool BuildSpellMissLog" "inline bool RemovedSpellMissLog" spell_h "${spell_h}")
elseif(MUTATION STREQUAL "spell_miss_sender")
    string(REPLACE "MopCombatLogPackets::BuildSpellMissLog(data, log);" "/* removed spell-miss serializer */" unit_cpp "${unit_cpp}")
elseif(MUTATION STREQUAL "spell_miss_registration")
    string(REPLACE "DefS(SMSG_SPELLLOGMISS, \"SMSG_SPELLLOGMISS\");" "/* removed spell-miss registration */" opcodes_cpp "${opcodes_cpp}")
elseif(MUTATION STREQUAL "spell_miss_gate")
    string(REPLACE "case SMSG_SPELLLOGMISS:" "case SMSG_UNKNOWN_0:" world_session "${world_session}")
elseif(MUTATION STREQUAL "spell_miss_reference")
    string(REPLACE "SMSG_SPELLLOGMISS                              0x1570  ACTIVE" "SMSG_SPELLLOGMISS                              0x1570  DORMANT" opcode_reference "${opcode_reference}")
elseif(MUTATION STREQUAL "spell_miss_count_width")
    string(REPLACE "out.WriteBits(uint32(log.targetCount), 23);" "out.WriteBits(uint32(log.targetCount), 22);" spell_h "${spell_h}")
elseif(MUTATION STREQUAL "spell_miss_count_bound")
    string(REPLACE "log.targetCount >= (size_t(1) << 23)" "log.targetCount >= (size_t(1) << 24)" spell_h "${spell_h}")
endif()

if(spell_packets MATCHES "SMSG_SPELLLOGEXECUTE")
    message(FATAL_ERROR "legacy execute-log opcode remains in SpellPackets.cpp")
endif()
if(unit_cpp MATCHES "SMSG_PERIODICAURALOG")
    message(FATAL_ERROR "legacy periodic-aura opcode remains in Unit.cpp")
endif()

foreach(sender IN ITEMS "${spell_packets}" "${unit_cpp}")
    if(NOT sender MATCHES "MopCombatLogPackets::Build")
        message(FATAL_ERROR "combat-log sender bypasses the shared 5.4.8 serializer")
    endif()
endforeach()

if(NOT spell_packets MATCHES "MopCombatLogPackets::BuildSpellExecuteLog")
    message(FATAL_ERROR "execute-log sender does not call the shared 18414 serializer")
endif()
if(NOT spell_packets MATCHES "SMSG_SPELL_EXECUTE_LOG")
    message(FATAL_ERROR "execute-log sender does not use the 18414 successor opcode")
endif()
if(NOT unit_cpp MATCHES "MopCombatLogPackets::BuildPeriodicAuraLog")
    message(FATAL_ERROR "periodic-aura sender does not call the shared 18414 serializer")
endif()
if(NOT unit_cpp MATCHES "SMSG_SPELL_PERIODIC_AURA_LOG")
    message(FATAL_ERROR "periodic-aura sender does not use the 18414 successor opcode")
endif()
if(NOT opcodes_cpp MATCHES "DefS\\(SMSG_SPELL_EXECUTE_LOG, \"SMSG_SPELL_EXECUTE_LOG\"\\)")
    message(FATAL_ERROR "execute-log successor lacks outbound opcode metadata")
endif()
if(NOT opcodes_cpp MATCHES "DefS\\(SMSG_SPELL_PERIODIC_AURA_LOG, \"SMSG_SPELL_PERIODIC_AURA_LOG\"\\)")
    message(FATAL_ERROR "periodic-aura successor lacks outbound opcode metadata")
endif()

foreach(sender IN ITEMS "${dispel_effect}" "${steal_effect}")
    if(NOT sender MATCHES "MopCombatLogPackets::BuildDispelLog")
        message(FATAL_ERROR "dispel/steal sender bypasses the shared 5.4.8 serializer")
    endif()
    if(NOT sender MATCHES "SMSG_SPELLDISPELLOG")
        message(FATAL_ERROR "dispel/steal sender does not use the merged 5.4.8 opcode")
    endif()
endforeach()
if(NOT dispel_effect MATCHES "log.isSteal = false" OR NOT steal_effect MATCHES "log.isSteal = true")
    message(FATAL_ERROR "dispel/steal call sites do not select distinct 5.4.8 event variants")
endif()
foreach(sender IN ITEMS "${dispel_effect}" "${steal_effect}")
    if(NOT sender MATCHES "log.isBreak = false")
        message(FATAL_ERROR "current dispel/steal path incorrectly selects an aura-break event")
    endif()
endforeach()
if(NOT dispel_effect MATCHES "RemoveAuraHolderDueToSpellByDispel" OR
   NOT dispel_effect MATCHES "SPELLCATEGORY_DEVOUR_MAGIC" OR
   NOT steal_effect MATCHES "RemoveAurasDueToSpellBySteal")
    message(FATAL_ERROR "combat-log migration removed a gameplay aura/heal side effect")
endif()
if(steal_effect MATCHES "SMSG_SPELLSTEALLOG" OR opcodes_h MATCHES "SMSG_SPELLSTEALLOG")
    message(FATAL_ERROR "obsolete standalone spell-steal opcode remains")
endif()
if(NOT opcodes_cpp MATCHES "DefS\\(SMSG_SPELLDISPELLOG, \"SMSG_SPELLDISPELLOG\"\\)")
    message(FATAL_ERROR "merged dispel/steal log lacks outbound opcode metadata")
endif()
if(NOT opcode_reference MATCHES "SMSG_SPELLDISPELLOG[ ]+0x0DF9  ACTIVE")
    message(FATAL_ERROR "reference inventory does not reflect active merged dispel/steal log")
endif()
if(NOT world_session MATCHES "case SMSG_SPELLDISPELLOG:")
    message(FATAL_ERROR "merged dispel/steal log remains blocked by enter-world suppression")
endif()

if(NOT spell_h MATCHES "BuildSpellInterruptLog")
    message(FATAL_ERROR "spell-interrupt serializer is absent from the owning spell code")
endif()
if(NOT interrupt_effect MATCHES "MopCombatLogPackets::BuildSpellInterruptLog" OR
   NOT interrupt_effect MATCHES "SMSG_SPELLINTERRUPTLOG")
    message(FATAL_ERROR "successful interrupt effects do not emit the 18414 interrupt log")
endif()
string(FIND "${interrupt_effect}" "MopCombatLogPackets::BuildSpellInterruptLog" interrupt_build_pos)
string(FIND "${interrupt_effect}" "unitTarget->InterruptSpell(CurrentSpellTypes(i), false);" interrupt_remove_pos)
if(interrupt_build_pos EQUAL -1 OR interrupt_remove_pos EQUAL -1 OR
   NOT interrupt_build_pos LESS interrupt_remove_pos)
    message(FATAL_ERROR "interrupt log is not built before the interrupted spell is removed")
endif()
if(NOT opcodes_cpp MATCHES "DefS\\(SMSG_SPELLINTERRUPTLOG, \"SMSG_SPELLINTERRUPTLOG\"\\)")
    message(FATAL_ERROR "spell-interrupt log lacks outbound opcode metadata")
endif()
if(NOT opcode_reference MATCHES "SMSG_SPELLINTERRUPTLOG[ ]+0x1851  ACTIVE")
    message(FATAL_ERROR "reference inventory does not reflect the active interrupt log")
endif()
if(NOT world_session MATCHES "case SMSG_SPELLINTERRUPTLOG:")
    message(FATAL_ERROR "spell-interrupt log remains blocked by enter-world suppression")
endif()

if(NOT spell_h MATCHES "BuildSpellInstakillLog")
    message(FATAL_ERROR "spell-instakill serializer is absent from the owning spell code")
endif()
if(NOT instakill_effect MATCHES "MopCombatLogPackets::BuildSpellInstakillLog" OR
   NOT instakill_effect MATCHES "SMSG_SPELLINSTAKILLLOG")
    message(FATAL_ERROR "instakill effect bypasses the 18414 instakill serializer")
endif()
if(NOT opcodes_cpp MATCHES "DefS\\(SMSG_SPELLINSTAKILLLOG, \"SMSG_SPELLINSTAKILLLOG\"\\)")
    message(FATAL_ERROR "spell-instakill log lacks outbound opcode metadata")
endif()
if(NOT opcode_reference MATCHES "SMSG_SPELLINSTAKILLLOG[ ]+0x09F8  ACTIVE")
    message(FATAL_ERROR "reference inventory does not reflect the active spell-instakill log")
endif()
if(NOT world_session MATCHES "case SMSG_SPELLINSTAKILLLOG:")
    message(FATAL_ERROR "spell-instakill log remains blocked by enter-world suppression")
endif()

if(NOT spell_h MATCHES "BuildSpellEnergizeLog")
    message(FATAL_ERROR "spell-energize serializer is absent from the owning spell code")
endif()
if(NOT unit_cpp MATCHES "MopCombatLogPackets::BuildSpellEnergizeLog" OR
   NOT unit_cpp MATCHES "SMSG_SPELLENERGIZELOG")
    message(FATAL_ERROR "energize sender bypasses the 18414 energize serializer")
endif()
if(NOT opcodes_cpp MATCHES "DefS\\(SMSG_SPELLENERGIZELOG, \"SMSG_SPELLENERGIZELOG\"\\)")
    message(FATAL_ERROR "spell-energize log lacks outbound opcode metadata")
endif()
if(NOT opcode_reference MATCHES "SMSG_SPELLENERGIZELOG[ ]+0x0D79  ACTIVE")
    message(FATAL_ERROR "reference inventory does not reflect the active spell-energize log")
endif()
if(NOT world_session MATCHES "case SMSG_SPELLENERGIZELOG:")
    message(FATAL_ERROR "spell-energize log remains blocked by enter-world suppression")
endif()

if(NOT spell_h MATCHES "BuildSpellHealLog")
    message(FATAL_ERROR "spell-heal serializer is absent from the owning spell code")
endif()
if(NOT unit_cpp MATCHES "MopCombatLogPackets::BuildSpellHealLog" OR
   NOT unit_cpp MATCHES "SMSG_SPELLHEALLOG")
    message(FATAL_ERROR "heal sender bypasses the 18414 heal serializer")
endif()
if(NOT opcodes_cpp MATCHES "DefS\\(SMSG_SPELLHEALLOG, \"SMSG_SPELLHEALLOG\"\\)")
    message(FATAL_ERROR "spell-heal log lacks outbound opcode metadata")
endif()
if(NOT opcode_reference MATCHES "SMSG_SPELLHEALLOG[ ]+0x09FB  ACTIVE")
    message(FATAL_ERROR "reference inventory does not reflect the active spell-heal log")
endif()
if(NOT world_session MATCHES "case SMSG_SPELLHEALLOG:")
    message(FATAL_ERROR "spell-heal log remains blocked by enter-world suppression")
endif()

if(NOT spell_h MATCHES "BuildSpellDamageShieldLog")
    message(FATAL_ERROR "damage-shield serializer is absent from the owning spell code")
endif()
if(NOT melee_damage_cpp MATCHES "MopCombatLogPackets::BuildSpellDamageShieldLog" OR
   NOT melee_damage_cpp MATCHES "SMSG_SPELLDAMAGESHIELD")
    message(FATAL_ERROR "damage-shield sender bypasses the 18414 serializer")
endif()
if(NOT opcodes_cpp MATCHES "DefS\\(SMSG_SPELLDAMAGESHIELD, \"SMSG_SPELLDAMAGESHIELD\"\\)")
    message(FATAL_ERROR "damage-shield log lacks outbound opcode metadata")
endif()
if(NOT opcode_reference MATCHES "SMSG_SPELLDAMAGESHIELD[ ]+0x05F3  ACTIVE")
    message(FATAL_ERROR "reference inventory does not reflect the active damage-shield log")
endif()
if(NOT world_session MATCHES "case SMSG_SPELLDAMAGESHIELD:")
    message(FATAL_ERROR "damage-shield log remains blocked by enter-world suppression")
endif()

if(NOT spell_h MATCHES "BuildSpellMissLog" OR
   NOT spell_h MATCHES "out.WriteBits\\(uint32\\(log.targetCount\\), 23\\)" OR
   NOT spell_h MATCHES "log.targetCount >= \\(size_t\\(1\\) << 23\\)")
    message(FATAL_ERROR "spell-miss serializer or its 23-bit count contract is absent")
endif()
if(NOT unit_cpp MATCHES "MopCombatLogPackets::BuildSpellMissLog" OR
   NOT unit_cpp MATCHES "SMSG_SPELLLOGMISS")
    message(FATAL_ERROR "spell-miss sender bypasses the 18414 serializer")
endif()
if(NOT opcodes_cpp MATCHES "DefS\\(SMSG_SPELLLOGMISS, \"SMSG_SPELLLOGMISS\"\\)")
    message(FATAL_ERROR "spell-miss log lacks outbound opcode metadata")
endif()
if(NOT opcode_reference MATCHES "SMSG_SPELLLOGMISS[ ]+0x1570  ACTIVE")
    message(FATAL_ERROR "reference inventory does not reflect the active spell-miss log")
endif()
if(NOT world_session MATCHES "case SMSG_SPELLLOGMISS:")
    message(FATAL_ERROR "spell-miss log remains blocked by enter-world suppression")
endif()
