file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/ItemHandlerVendor.cpp" vendor_handler)
file(READ "${SOURCE_ROOT}/src/game/Object/PlayerItemStorage.cpp" item_storage)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" opcode_registry)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.h" opcode_header)
file(READ "${SOURCE_ROOT}/src/game/Server/WorldSession.cpp" world_session)

if(MUTATION STREQUAL "request_reader")
    string(REPLACE "MopItemPackets::ReadListInventory(recv_data)" "ObjectGuid()" vendor_handler "${vendor_handler}")
elseif(MUTATION STREQUAL "response_builder")
    string(REPLACE "MopItemPackets::BuildVendorList(data, vendorList)" "data.Initialize(SMSG_LIST_INVENTORY)" vendor_handler "${vendor_handler}")
elseif(MUTATION STREQUAL "client_registration")
    string(REPLACE "DefC(CMSG_LIST_INVENTORY," "DefC(CMSG_UNUSED_LIST_INVENTORY," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "server_registration")
    string(REPLACE "DefS(SMSG_LIST_INVENTORY," "DefS(SMSG_UNUSED_LIST_INVENTORY," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "whitelist")
    string(REPLACE "case SMSG_LIST_INVENTORY:" "case SMSG_UNUSED_LIST_INVENTORY:" world_session "${world_session}")
elseif(MUTATION STREQUAL "sell_request_reader")
    string(REPLACE "MopItemPackets::ParseSellItem(recv_data, request)" "false" vendor_handler "${vendor_handler}")
elseif(MUTATION STREQUAL "sell_response_builder")
    string(REPLACE "MopItemPackets::BuildSellResult(data," "MopItemPackets::BuildUnusedSellResult(data," item_storage "${item_storage}")
elseif(MUTATION STREQUAL "sell_client_registration")
    string(REPLACE "DefC(CMSG_SELL_ITEM," "DefC(CMSG_UNUSED_SELL_ITEM," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "sell_server_registration")
    string(REPLACE "DefS(SMSG_SELL_ITEM," "DefS(SMSG_UNUSED_SELL_ITEM," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "sell_whitelist")
    string(REPLACE "case SMSG_SELL_ITEM:" "case SMSG_UNUSED_SELL_ITEM:" world_session "${world_session}")
endif()

string(FIND "${vendor_handler}" "MopItemPackets::ReadListInventory(recv_data)" request_reader)
if(request_reader EQUAL -1)
    message(FATAL_ERROR "vendor list handler bypasses the 18414 request reader")
endif()
string(FIND "${vendor_handler}" "MopItemPackets::BuildVendorList(data, vendorList)" response_builder)
if(response_builder EQUAL -1)
    message(FATAL_ERROR "vendor list sender bypasses the 18414 response builder")
endif()
string(FIND "${vendor_handler}" "data.WriteBits(count, 21)" legacy_count)
if(NOT legacy_count EQUAL -1)
    message(FATAL_ERROR "legacy 21-bit vendor item count remains")
endif()
string(FIND "${opcode_registry}" "DefC(CMSG_LIST_INVENTORY, \"CMSG_LIST_INVENTORY\"" client_registration)
if(client_registration EQUAL -1)
    message(FATAL_ERROR "CMSG_LIST_INVENTORY is not registered")
endif()
string(FIND "${opcode_registry}" "DefS(SMSG_LIST_INVENTORY, \"SMSG_LIST_INVENTORY\")" server_registration)
if(server_registration EQUAL -1)
    message(FATAL_ERROR "SMSG_LIST_INVENTORY is missing outbound metadata")
endif()
string(FIND "${world_session}" "case SMSG_LIST_INVENTORY:" whitelist)
if(whitelist EQUAL -1)
    message(FATAL_ERROR "SMSG_LIST_INVENTORY is not admitted through send suppression")
endif()
string(FIND "${opcode_header}" "CMSG_LIST_INVENTORY                          = 0x02D8" client_value)
if(client_value EQUAL -1)
    message(FATAL_ERROR "CMSG_LIST_INVENTORY value drifted")
endif()
string(FIND "${opcode_header}" "SMSG_LIST_INVENTORY                          = 0x1AAE" server_value)
if(server_value EQUAL -1)
    message(FATAL_ERROR "SMSG_LIST_INVENTORY value drifted")
endif()

string(FIND "${vendor_handler}" "MopItemPackets::ParseSellItem(recv_data, request)" sell_request_reader)
if(sell_request_reader EQUAL -1)
    message(FATAL_ERROR "sell handler bypasses the 18414 request reader")
endif()
string(FIND "${item_storage}" "MopItemPackets::BuildSellResult(data," sell_response_builder)
if(sell_response_builder EQUAL -1)
    message(FATAL_ERROR "sell error sender bypasses the 18414 response builder")
endif()
string(FIND "${opcode_registry}" "DefC(CMSG_SELL_ITEM, \"CMSG_SELL_ITEM\"" sell_client_registration)
if(sell_client_registration EQUAL -1)
    message(FATAL_ERROR "CMSG_SELL_ITEM is not registered")
endif()
string(FIND "${opcode_registry}" "DefS(SMSG_SELL_ITEM, \"SMSG_SELL_ITEM\")" sell_server_registration)
if(sell_server_registration EQUAL -1)
    message(FATAL_ERROR "SMSG_SELL_ITEM is missing outbound metadata")
endif()
string(FIND "${world_session}" "case SMSG_SELL_ITEM:" sell_whitelist)
if(sell_whitelist EQUAL -1)
    message(FATAL_ERROR "SMSG_SELL_ITEM is not admitted through send suppression")
endif()
string(FIND "${opcode_header}" "CMSG_SELL_ITEM                               = 0x1358" sell_client_value)
if(sell_client_value EQUAL -1)
    message(FATAL_ERROR "CMSG_SELL_ITEM value drifted")
endif()
string(FIND "${opcode_header}" "SMSG_SELL_ITEM                               = 0x048E" sell_server_value)
if(sell_server_value EQUAL -1)
    message(FATAL_ERROR "SMSG_SELL_ITEM value drifted")
endif()
