file(READ "${SOURCE_ROOT}/src/game/Object/CurrencyMgr.cpp" currency_mgr)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" opcode_registry)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.h" opcode_header)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes_reference.h" opcode_reference)
file(READ "${SOURCE_ROOT}/src/game/Server/WorldSession.cpp" world_session)

if(MUTATION STREQUAL "weekly_registration")
    string(REPLACE "DefS(SMSG_WEEKLY_RESET_CURRENCIES," "DefS(SMSG_UNUSED_WEEKLY_RESET_CURRENCIES," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "weekly_admission")
    string(REPLACE "case SMSG_WEEKLY_RESET_CURRENCIES:" "case SMSG_UNUSED_WEEKLY_RESET_CURRENCIES:" world_session "${world_session}")
elseif(MUTATION STREQUAL "weekly_body")
    string(REPLACE "WorldPacket data(SMSG_WEEKLY_RESET_CURRENCIES, 0);" "WorldPacket data(SMSG_WEEKLY_RESET_CURRENCIES, 4);" currency_mgr "${currency_mgr}")
elseif(MUTATION STREQUAL "weekly_value")
    string(REPLACE "SMSG_WEEKLY_RESET_CURRENCIES                 = 0x023E" "SMSG_WEEKLY_RESET_CURRENCIES                 = 0x0000" opcode_header "${opcode_header}")
elseif(MUTATION STREQUAL "weekly_reference")
    string(REPLACE "SMSG_WEEKLY_RESET_CURRENCY                     0x023E  ACTIVE" "SMSG_WEEKLY_RESET_CURRENCY                     0x023E  DORMANT" opcode_reference "${opcode_reference}")
endif()

foreach(legacy_symbol IN ITEMS SMSG_SET_CURRENCY SMSG_SEND_CURRENCIES)
    if(currency_mgr MATCHES "${legacy_symbol}([^A-Za-z0-9_]|$)")
        message(FATAL_ERROR "legacy ${legacy_symbol} remains in CurrencyMgr.cpp")
    endif()
endforeach()

foreach(builder_name IN ITEMS BuildUpdateCurrency BuildSetupCurrency)
    if(NOT currency_mgr MATCHES "MopCurrencyPackets::${builder_name}")
        message(FATAL_ERROR "CurrencyMgr.cpp does not use ${builder_name}")
    endif()
endforeach()

foreach(server_name IN ITEMS SMSG_UPDATE_CURRENCY SMSG_SETUP_CURRENCY SMSG_WEEKLY_RESET_CURRENCIES)
    if(NOT opcode_registry MATCHES "DefS\\(${server_name},[ \\t]*\\\"${server_name}\\\"\\)")
        message(FATAL_ERROR "${server_name} is missing outbound opcode metadata")
    endif()
endforeach()

if(NOT world_session MATCHES "case SMSG_WEEKLY_RESET_CURRENCIES:")
    message(FATAL_ERROR "SMSG_WEEKLY_RESET_CURRENCIES is missing sender admission")
endif()

if(NOT currency_mgr MATCHES "WorldPacket data\\(SMSG_WEEKLY_RESET_CURRENCIES,[ \\t]*0\\);")
    message(FATAL_ERROR "weekly currency reset is no longer the binary-proved empty body")
endif()

if(NOT opcode_header MATCHES "SMSG_WEEKLY_RESET_CURRENCIES[ \\t]*=[ \\t]*0x023E")
    message(FATAL_ERROR "weekly currency reset opcode value drifted")
endif()

if(NOT opcode_reference MATCHES "SMSG_WEEKLY_RESET_CURRENCY[ \\t]+0x023E[ \\t]+ACTIVE")
    message(FATAL_ERROR "weekly currency reset reference status is stale")
endif()
