file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/ItemHandlerVendor.cpp" vendor_handler)
file(READ "${SOURCE_ROOT}/src/game/Object/PlayerItemStorage.cpp" item_storage)
file(READ "${SOURCE_ROOT}/src/game/Object/PlayerVendor.cpp" player_vendor)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" opcode_registry)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.h" opcode_header)
file(READ "${SOURCE_ROOT}/src/game/Server/WorldSession.cpp" world_session)

if(MUTATION STREQUAL "request_reader")
    string(REPLACE "MopItemPackets::ReadListInventory(recv_data)" "ObjectGuid()" vendor_handler "${vendor_handler}")
elseif(MUTATION STREQUAL "response_builder")
    string(REPLACE "MopItemPackets::BuildVendorList(data, vendorList)" "data.Initialize(SMSG_LIST_INVENTORY)" vendor_handler "${vendor_handler}")
elseif(MUTATION STREQUAL "client_registration")
    string(REPLACE "DefC(CMSG_LIST_INVENTORY," "DefC(CMSG_UNUSED_LIST_INVENTORY," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "server_registration")
    string(REPLACE "DefS(SMSG_LIST_INVENTORY," "DefS(SMSG_UNUSED_LIST_INVENTORY," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "whitelist")
    string(REPLACE "case SMSG_LIST_INVENTORY:" "case SMSG_UNUSED_LIST_INVENTORY:" world_session "${world_session}")
elseif(MUTATION STREQUAL "sell_request_reader")
    string(REPLACE "MopItemPackets::ParseSellItem(recv_data, request)" "false" vendor_handler "${vendor_handler}")
elseif(MUTATION STREQUAL "sell_response_builder")
    string(REPLACE "MopItemPackets::BuildSellResult(data," "MopItemPackets::BuildUnusedSellResult(data," item_storage "${item_storage}")
elseif(MUTATION STREQUAL "sell_client_registration")
    string(REPLACE "DefC(CMSG_SELL_ITEM," "DefC(CMSG_UNUSED_SELL_ITEM," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "sell_server_registration")
    string(REPLACE "DefS(SMSG_SELL_ITEM," "DefS(SMSG_UNUSED_SELL_ITEM," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "sell_whitelist")
    string(REPLACE "case SMSG_SELL_ITEM:" "case SMSG_UNUSED_SELL_ITEM:" world_session "${world_session}")
elseif(MUTATION STREQUAL "buy_request_reader")
    string(REPLACE "MopItemPackets::ParseBuyItem(recv_data, request)" "false" vendor_handler "${vendor_handler}")
elseif(MUTATION STREQUAL "buy_success_builder")
    string(REPLACE "MopItemPackets::BuildBuyItemResult(data," "MopItemPackets::BuildUnusedBuyItemResult(data," player_vendor "${player_vendor}")
elseif(MUTATION STREQUAL "buy_failure_builder")
    string(REPLACE "MopItemPackets::BuildBuyFailed(data," "MopItemPackets::BuildUnusedBuyFailed(data," item_storage "${item_storage}")
elseif(MUTATION STREQUAL "buy_client_registration")
    string(REPLACE "DefC(CMSG_BUY_ITEM," "DefC(CMSG_UNUSED_BUY_ITEM," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "buy_success_registration")
    string(REPLACE "DefS(SMSG_BUY_ITEM," "DefS(SMSG_UNUSED_BUY_ITEM," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "buy_failure_registration")
    string(REPLACE "DefS(SMSG_BUY_FAILED," "DefS(SMSG_UNUSED_BUY_FAILED," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "buy_success_whitelist")
    string(REPLACE "case SMSG_BUY_ITEM:" "case SMSG_UNUSED_BUY_ITEM:" world_session "${world_session}")
elseif(MUTATION STREQUAL "buy_failure_whitelist")
    string(REPLACE "case SMSG_BUY_FAILED:" "case SMSG_UNUSED_BUY_FAILED:" world_session "${world_session}")
elseif(MUTATION STREQUAL "buy_legacy_request")
    string(APPEND vendor_handler "\nrecv_data >> vendorGuid >> type >> item >> slot >> count >> bagGuid >> bagSlot;\n")
elseif(MUTATION STREQUAL "buy_legacy_success")
    string(APPEND player_vendor "\nWorldPacket data(SMSG_BUY_ITEM, 8 + 4 + 4 + 4);\n")
elseif(MUTATION STREQUAL "buy_legacy_failure")
    string(APPEND item_storage "\nWorldPacket data(SMSG_BUY_FAILED, (8 + 4 + 4 + 1));\n")
endif()

string(FIND "${vendor_handler}" "MopItemPackets::ReadListInventory(recv_data)" request_reader)
if(request_reader EQUAL -1)
    message(FATAL_ERROR "vendor list handler bypasses the 18414 request reader")
endif()
string(FIND "${vendor_handler}" "MopItemPackets::BuildVendorList(data, vendorList)" response_builder)
if(response_builder EQUAL -1)
    message(FATAL_ERROR "vendor list sender bypasses the 18414 response builder")
endif()
string(FIND "${vendor_handler}" "data.WriteBits(count, 21)" legacy_count)
if(NOT legacy_count EQUAL -1)
    message(FATAL_ERROR "legacy 21-bit vendor item count remains")
endif()
string(FIND "${opcode_registry}" "DefC(CMSG_LIST_INVENTORY, \"CMSG_LIST_INVENTORY\"" client_registration)
if(client_registration EQUAL -1)
    message(FATAL_ERROR "CMSG_LIST_INVENTORY is not registered")
endif()
string(FIND "${opcode_registry}" "DefS(SMSG_LIST_INVENTORY, \"SMSG_LIST_INVENTORY\")" server_registration)
if(server_registration EQUAL -1)
    message(FATAL_ERROR "SMSG_LIST_INVENTORY is missing outbound metadata")
endif()
string(FIND "${world_session}" "case SMSG_LIST_INVENTORY:" whitelist)
if(whitelist EQUAL -1)
    message(FATAL_ERROR "SMSG_LIST_INVENTORY is not admitted through send suppression")
endif()
string(FIND "${opcode_header}" "CMSG_LIST_INVENTORY                          = 0x02D8" client_value)
if(client_value EQUAL -1)
    message(FATAL_ERROR "CMSG_LIST_INVENTORY value drifted")
endif()
string(FIND "${opcode_header}" "SMSG_LIST_INVENTORY                          = 0x1AAE" server_value)
if(server_value EQUAL -1)
    message(FATAL_ERROR "SMSG_LIST_INVENTORY value drifted")
endif()

string(FIND "${vendor_handler}" "MopItemPackets::ParseSellItem(recv_data, request)" sell_request_reader)
if(sell_request_reader EQUAL -1)
    message(FATAL_ERROR "sell handler bypasses the 18414 request reader")
endif()
string(FIND "${item_storage}" "MopItemPackets::BuildSellResult(data," sell_response_builder)
if(sell_response_builder EQUAL -1)
    message(FATAL_ERROR "sell error sender bypasses the 18414 response builder")
endif()
string(FIND "${opcode_registry}" "DefC(CMSG_SELL_ITEM, \"CMSG_SELL_ITEM\"" sell_client_registration)
if(sell_client_registration EQUAL -1)
    message(FATAL_ERROR "CMSG_SELL_ITEM is not registered")
endif()
string(FIND "${opcode_registry}" "DefS(SMSG_SELL_ITEM, \"SMSG_SELL_ITEM\")" sell_server_registration)
if(sell_server_registration EQUAL -1)
    message(FATAL_ERROR "SMSG_SELL_ITEM is missing outbound metadata")
endif()
string(FIND "${world_session}" "case SMSG_SELL_ITEM:" sell_whitelist)
if(sell_whitelist EQUAL -1)
    message(FATAL_ERROR "SMSG_SELL_ITEM is not admitted through send suppression")
endif()
string(FIND "${opcode_header}" "CMSG_SELL_ITEM                               = 0x1358" sell_client_value)
if(sell_client_value EQUAL -1)
    message(FATAL_ERROR "CMSG_SELL_ITEM value drifted")
endif()
string(FIND "${opcode_header}" "SMSG_SELL_ITEM                               = 0x048E" sell_server_value)
if(sell_server_value EQUAL -1)
    message(FATAL_ERROR "SMSG_SELL_ITEM value drifted")
endif()

string(FIND "${vendor_handler}" "MopItemPackets::ParseBuyItem(recv_data, request)" buy_request_reader)
if(buy_request_reader EQUAL -1)
    message(FATAL_ERROR "buy handler bypasses the 18414 request reader")
endif()
string(FIND "${player_vendor}" "MopItemPackets::BuildBuyItemResult(data," buy_success_builder)
if(buy_success_builder EQUAL -1)
    message(FATAL_ERROR "buy success sender bypasses the 18414 response builder")
endif()
string(FIND "${item_storage}" "MopItemPackets::BuildBuyFailed(data," buy_failure_builder)
if(buy_failure_builder EQUAL -1)
    message(FATAL_ERROR "buy failure sender bypasses the 18414 response builder")
endif()
string(FIND "${opcode_registry}" "DefC(CMSG_BUY_ITEM, \"CMSG_BUY_ITEM\"" buy_client_registration)
if(buy_client_registration EQUAL -1)
    message(FATAL_ERROR "CMSG_BUY_ITEM is not registered")
endif()
string(FIND "${opcode_registry}" "DefS(SMSG_BUY_ITEM, \"SMSG_BUY_ITEM\")" buy_success_registration)
if(buy_success_registration EQUAL -1)
    message(FATAL_ERROR "SMSG_BUY_ITEM is missing outbound metadata")
endif()
string(FIND "${opcode_registry}" "DefS(SMSG_BUY_FAILED, \"SMSG_BUY_FAILED\")" buy_failure_registration)
if(buy_failure_registration EQUAL -1)
    message(FATAL_ERROR "SMSG_BUY_FAILED is missing outbound metadata")
endif()
string(FIND "${world_session}" "case SMSG_BUY_ITEM:" buy_success_whitelist)
if(buy_success_whitelist EQUAL -1)
    message(FATAL_ERROR "SMSG_BUY_ITEM is not admitted through send suppression")
endif()
string(FIND "${world_session}" "case SMSG_BUY_FAILED:" buy_failure_whitelist)
if(buy_failure_whitelist EQUAL -1)
    message(FATAL_ERROR "SMSG_BUY_FAILED is not admitted through send suppression")
endif()
foreach(value IN ITEMS
        "CMSG_BUY_ITEM                                = 0x02E2"
        "SMSG_BUY_ITEM                                = 0x101A"
        "SMSG_BUY_FAILED                              = 0x1563")
    string(FIND "${opcode_header}" "${value}" buy_value)
    if(buy_value EQUAL -1)
        message(FATAL_ERROR "18414 buy opcode value drifted: ${value}")
    endif()
endforeach()
string(FIND "${vendor_handler}" "recv_data >> vendorGuid >> type >> item >> slot >> count >> bagGuid >> bagSlot" buy_legacy_request)
if(NOT buy_legacy_request EQUAL -1)
    message(FATAL_ERROR "legacy dense buy request reader remains")
endif()
string(FIND "${player_vendor}" "WorldPacket data(SMSG_BUY_ITEM, 8 + 4 + 4 + 4)" buy_legacy_success)
if(NOT buy_legacy_success EQUAL -1)
    message(FATAL_ERROR "legacy dense buy-success sender remains")
endif()
string(FIND "${item_storage}" "WorldPacket data(SMSG_BUY_FAILED, (8 + 4 + 4 + 1))" buy_legacy_failure)
if(NOT buy_legacy_failure EQUAL -1)
    message(FATAL_ERROR "legacy dense buy-failure sender remains")
endif()
