if(NOT DEFINED SOURCE_ROOT)
    message(FATAL_ERROR "SOURCE_ROOT is required")
endif()

file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/Mail.h" mail_header)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/MailMoneyPolicy.h" policy_header)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/Mail.cpp" mail_source)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/MailHandler.cpp" mail_handler)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/MopMailPackets.h" packet_builder)
file(READ "${SOURCE_ROOT}/src/game/Object/PlayerLoad.cpp" player_load)
file(READ "${SOURCE_ROOT}/src/game/Object/PlayerSave.cpp" player_save)
file(READ "${SOURCE_ROOT}/src/game/Object/ObjectMgr.cpp" object_mgr)
file(READ "${SOURCE_ROOT}/src/game/Object/Player.cpp" player_source)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" opcode_registry)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes_reference.h" opcode_reference)

function(require_literal_once content needle context)
    set(remaining "${content}")
    set(count 0)
    while(TRUE)
        string(FIND "${remaining}" "${needle}" position)
        if(position EQUAL -1)
            break()
        endif()
        math(EXPR count "${count} + 1")
        math(EXPR next_position "${position} + 1")
        string(SUBSTRING "${remaining}" ${next_position} -1 remaining)
    endwhile()
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "${context}: expected one literal, found ${count}")
    endif()
endfunction()

function(require_none content needle context)
    string(FIND "${content}" "${needle}" position)
    if(NOT position EQUAL -1)
        message(FATAL_ERROR "${context}: forbidden literal remains")
    endif()
endfunction()

function(replace_literal_once variable old_value new_value mutation_name)
    set(content "${${variable}}")
    set(remaining "${content}")
    set(count 0)
    while(TRUE)
        string(FIND "${remaining}" "${old_value}" position)
        if(position EQUAL -1)
            break()
        endif()
        math(EXPR count "${count} + 1")
        math(EXPR next_position "${position} + 1")
        string(SUBSTRING "${remaining}" ${next_position} -1 remaining)
    endwhile()
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "mutation target unavailable or ambiguous: ${mutation_name}: found ${count}")
    endif()
    string(REPLACE "${old_value}" "${new_value}" content "${content}")
    set(${variable} "${content}" PARENT_SCOPE)
endfunction()

set(wide_insert [=["VALUES ('%u', '%u', '%u', '%u', '%u', '%u', '%s', '%s', '%u', '" UI64FMTD "', '" UI64FMTD "', '" UI64FMTD "', '" UI64FMTD "', '%u')",]=])
set(narrow_money_insert [=["VALUES ('%u', '%u', '%u', '%u', '%u', '%u', '%s', '%s', '%u', '" UI64FMTD "', '" UI64FMTD "', '%u', '" UI64FMTD "', '%u')",]=])
set(narrow_cod_insert [=["VALUES ('%u', '%u', '%u', '%u', '%u', '%u', '%s', '%s', '%u', '" UI64FMTD "', '" UI64FMTD "', '" UI64FMTD "', '%u', '%u')",]=])
set(wide_send_log [=[DEBUG_LOG("%s is sending mail to %s with subject %s and body %s includes %u items, " UI64FMTD " copper and " UI64FMTD " COD copper with unk1 = %u, unk2 = %u",]=])
set(narrow_send_log [=[DEBUG_LOG("%s is sending mail to %s with subject %s and body %s includes %u items, %u copper and %u COD copper with unk1 = %u, unk2 = %u",]=])

if(DEFINED MUTATION)
    if(MUTATION_TARGET_DRIFT_PROBE)
        string(REPLACE "SetCOD(uint64 COD)" "SetCOD(uint64 value)" mail_header "${mail_header}")
    endif()

    if(MUTATION STREQUAL "setcod_uint32")
        replace_literal_once(mail_header "SetCOD(uint64 COD)" "SetCOD(uint32 COD)" "${MUTATION}")
    elseif(MUTATION STREQUAL "insert_money_format")
        replace_literal_once(mail_source "${wide_insert}" "${narrow_money_insert}" "${MUTATION}")
    elseif(MUTATION STREQUAL "insert_cod_format")
        replace_literal_once(mail_source "${wide_insert}" "${narrow_cod_insert}" "${MUTATION}")
    elseif(MUTATION STREQUAL "insert_money_cast")
        replace_literal_once(mail_source "uint64(m_money)" "uint32(m_money)" "${MUTATION}")
    elseif(MUTATION STREQUAL "insert_cod_cast")
        replace_literal_once(mail_source "uint64(m_COD)" "uint32(m_COD)" "${MUTATION}")
    elseif(MUTATION STREQUAL "load_money_uint32")
        replace_literal_once(player_load "m->money = fields[8].GetUInt64();" "m->money = fields[8].GetUInt32();" "${MUTATION}")
    elseif(MUTATION STREQUAL "load_cod_uint32")
        replace_literal_once(player_load "m->COD = fields[9].GetUInt64();" "m->COD = fields[9].GetUInt32();" "${MUTATION}")
    elseif(MUTATION STREQUAL "save_money_uint32")
        replace_literal_once(player_save "stmt.addUInt64(m->money);" "stmt.addUInt32(m->money);" "${MUTATION}")
    elseif(MUTATION STREQUAL "save_cod_uint32")
        replace_literal_once(player_save "stmt.addUInt64(m->COD);" "stmt.addUInt32(m->COD);" "${MUTATION}")
    elseif(MUTATION STREQUAL "expired_cod_uint32")
        replace_literal_once(object_mgr "m->COD = fields[6].GetUInt64();" "m->COD = fields[6].GetUInt32();" "${MUTATION}")
    elseif(MUTATION STREQUAL "delete_return_money_uint32")
        replace_literal_once(player_source "uint64 money         = fields[6].GetUInt64();" "uint64 money         = fields[6].GetUInt32();" "${MUTATION}")
    elseif(MUTATION STREQUAL "send_debug_money_u32")
        replace_literal_once(mail_handler "${wide_send_log}" "${narrow_send_log}" "${MUTATION}")
    elseif(MUTATION STREQUAL "packet_cod_uint32")
        replace_literal_once(packet_builder "uint64 cod = 0;" "uint32 cod = 0;" "${MUTATION}")
    elseif(MUTATION STREQUAL "packet_money_uint32")
        replace_literal_once(packet_builder "uint64 money = 0;" "uint32 money = 0;" "${MUTATION}")
    elseif(MUTATION STREQUAL "cod_limit_plus_one")
        replace_literal_once(policy_header "MAX_PLAYER_COD = UI64LIT(100000000)" "MAX_PLAYER_COD = UI64LIT(100000001)" "${MUTATION}")
    elseif(MUTATION STREQUAL "cod_exclusive_limit")
        replace_literal_once(policy_header "return cod <= MAX_PLAYER_COD;" "return cod < MAX_PLAYER_COD;" "${MUTATION}")
    elseif(MUTATION STREQUAL "debit_addition")
        replace_literal_once(policy_header "return fee <= current && amount <= current - fee;" "return amount + fee <= current;" "${MUTATION}")
    elseif(MUTATION STREQUAL "debit_drop_fee_guard")
        replace_literal_once(policy_header "return fee <= current && amount <= current - fee;" "return amount <= current - fee;" "${MUTATION}")
    elseif(MUTATION STREQUAL "credit_addition")
        replace_literal_once(policy_header "return current <= limit && amount <= limit - current;" "return current + amount <= limit;" "${MUTATION}")
    elseif(MUTATION STREQUAL "credit_drop_current_guard")
        replace_literal_once(policy_header "return current <= limit && amount <= limit - current;" "return amount <= limit - current;" "${MUTATION}")
    elseif(MUTATION STREQUAL "register_take_money")
        string(APPEND opcode_registry "\nDefC(CMSG_MAIL_TAKE_MONEY, STATUS_LOGGEDIN, PROCESS_THREADUNSAFE, &WorldSession::HandleMailTakeMoney);\n")
    elseif(MUTATION STREQUAL "activate_take_money")
        replace_literal_once(opcode_reference "CMSG_MAIL_TAKE_MONEY                           0x06FA  DORMANT" "CMSG_MAIL_TAKE_MONEY                           0x06FA  ACTIVE" "${MUTATION}")
    elseif(MUTATION STREQUAL "register_send_mail")
        string(APPEND opcode_registry "\nDefC(CMSG_SEND_MAIL, STATUS_LOGGEDIN, PROCESS_THREADUNSAFE, &WorldSession::HandleSendMail);\n")
    elseif(MUTATION STREQUAL "activate_send_mail")
        replace_literal_once(opcode_reference "CMSG_SEND_MAIL                                 0x1DBA  DORMANT" "CMSG_SEND_MAIL                                 0x1DBA  ACTIVE" "${MUTATION}")
    else()
        message(FATAL_ERROR "unknown mail money width mutation: ${MUTATION}")
    endif()
endif()

require_literal_once("${mail_header}" "SetCOD(uint64 COD)" "MailDraft COD setter width")
require_literal_once("${policy_header}" "MAX_PLAYER_COD = UI64LIT(100000000)" "inclusive player COD maximum")
require_literal_once("${policy_header}" "return cod <= MAX_PLAYER_COD;" "inclusive player COD predicate")
require_literal_once("${policy_header}" "return fee <= current && amount <= current - fee;" "overflow-safe debit predicate")
require_literal_once("${policy_header}" "return current <= limit && amount <= limit - current;" "overflow-safe credit predicate")
require_literal_once("${player_load}" "m->money = fields[8].GetUInt64();" "login money read width")
require_literal_once("${player_load}" "m->COD = fields[9].GetUInt64();" "login COD read width")
require_literal_once("${player_save}" "stmt.addUInt64(m->money);" "dirty-mail money bind width")
require_literal_once("${player_save}" "stmt.addUInt64(m->COD);" "dirty-mail COD bind width")
require_literal_once("${object_mgr}" "m->COD = fields[6].GetUInt64();" "expired-mail COD read width")
require_literal_once("${player_source}" "uint64 money         = fields[6].GetUInt64();" "delete-return money read width")
require_literal_once("${packet_builder}" "uint64 cod = 0;" "mail-list COD field width")
require_literal_once("${packet_builder}" "uint64 money = 0;" "mail-list money field width")
require_literal_once("${packet_builder}" "out << mail.mailTemplateId << mail.cod;" "mail-list COD writer")
require_literal_once("${packet_builder}" "mail.daysLeft << mail.money" "mail-list money writer")
require_literal_once("${mail_source}" "${wide_insert}" "mail insert format widths")
require_literal_once("${mail_source}" "uint64(m_money)" "mail insert money argument width")
require_literal_once("${mail_source}" "uint64(m_COD)" "mail insert COD argument width")
require_literal_once("${mail_handler}" "${wide_send_log}" "send-mail diagnostic widths")
require_none("${opcode_registry}" "DefC(CMSG_MAIL_TAKE_MONEY" "CMSG_MAIL_TAKE_MONEY registration")
require_none("${opcode_registry}" "DefC(CMSG_SEND_MAIL" "CMSG_SEND_MAIL registration")
require_literal_once("${opcode_reference}" "CMSG_MAIL_TAKE_MONEY                           0x06FA  DORMANT" "CMSG_MAIL_TAKE_MONEY dormant reference")
require_literal_once("${opcode_reference}" "CMSG_SEND_MAIL                                 0x1DBA  DORMANT" "CMSG_SEND_MAIL dormant reference")
