# SPDX-License-Identifier: GPL-3.0-or-later

if(NOT DEFINED SOURCE_ROOT)
    message(FATAL_ERROR "SOURCE_ROOT is required")
endif()

file(READ "${SOURCE_ROOT}/src/game/Object/PlayerTaxi.cpp" PLAYER_TAXI_CPP)
file(READ "${SOURCE_ROOT}/src/game/Object/PlayerTaxi.h" PLAYER_TAXI_H)

if(DEFINED MUTATION)
    if(MUTATION STREQUAL "every_token_faction")
        string(REPLACE "ParseTaxiPersistenceValue(*token, factionId)"
            "ParseTaxiPersistenceValue(tokens.back(), factionId)" PLAYER_TAXI_CPP "${PLAYER_TAXI_CPP}")
    elseif(MUTATION STREQUAL "every_token_node")
        string(REPLACE "++token;" "token = tokens.begin();" PLAYER_TAXI_CPP "${PLAYER_TAXI_CPP}")
    elseif(MUTATION STREQUAL "skip_min_nodes")
        string(REPLACE "if (nodes.size() < 2)" "if (false)" PLAYER_TAXI_CPP "${PLAYER_TAXI_CPP}")
    elseif(MUTATION STREQUAL "skip_node_validation")
        string(REPLACE "if (!taxi.IsValidNodeId(node))" "if (false)" PLAYER_TAXI_CPP "${PLAYER_TAXI_CPP}")
    elseif(MUTATION STREQUAL "skip_route_validation")
        string(REPLACE "if (!validator.HasTaxiPath(nodes[i - 1], nodes[i]))" "if (false)" PLAYER_TAXI_CPP "${PLAYER_TAXI_CPP}")
    elseif(MUTATION STREQUAL "skip_mount_validation")
        string(REPLACE "if (!validator.HasTaxiMount(nodes.front(), team))" "if (false)" PLAYER_TAXI_CPP "${PLAYER_TAXI_CPP}")
    elseif(MUTATION STREQUAL "allow_exception_escape")
        string(REPLACE "catch (...)" "catch (TaxiPersistenceMutationNeverCaught)" PLAYER_TAXI_CPP "${PLAYER_TAXI_CPP}")
    elseif(MUTATION STREQUAL "keep_partial_state")
        string(REPLACE "ResetTaxiPersistenceState(taxi);" "" PLAYER_TAXI_CPP "${PLAYER_TAXI_CPP}")
    elseif(MUTATION STREQUAL "continue_debits_fare")
        string(REPLACE "GetSession()->SendDoFlight(mountDisplayId, path, startNode);"
            "ModifyMoney(-1);\n    GetSession()->SendDoFlight(mountDisplayId, path, startNode);"
            PLAYER_TAXI_CPP "${PLAYER_TAXI_CPP}")
    else()
        message(FATAL_ERROR "Unknown mutation: ${MUTATION}")
    endif()
endif()

function(require_text HAYSTACK NEEDLE LABEL)
    string(FIND "${${HAYSTACK}}" "${NEEDLE}" POSITION)
    if(POSITION EQUAL -1)
        message(FATAL_ERROR "Missing ${LABEL}")
    endif()
endfunction()

require_text(PLAYER_TAXI_CPP "ParseTaxiPersistenceValue(*token, factionId)" "single faction-token parse")
require_text(PLAYER_TAXI_CPP "++token;" "advance past faction token")
require_text(PLAYER_TAXI_CPP "if (nodes.size() < 2)" "two-node minimum")
require_text(PLAYER_TAXI_CPP "if (!taxi.IsValidNodeId(node))" "checked node validation")
require_text(PLAYER_TAXI_CPP "if (!validator.HasTaxiPath(nodes[i - 1], nodes[i]))" "adjacent route validation")
require_text(PLAYER_TAXI_CPP "if (!validator.HasTaxiMount(nodes.front(), team))" "mount validation")
require_text(PLAYER_TAXI_CPP "catch (...)" "exception boundary")
require_text(PLAYER_TAXI_CPP "ResetTaxiPersistenceState(taxi);" "failure-state reset")
require_text(PLAYER_TAXI_CPP "return TaxiPersistence::LoadTaxiDestinations(*this, values, team, validator);" "production loader delegation")
require_text(PLAYER_TAXI_H "class Validator" "validation seam declaration")

string(FIND "${PLAYER_TAXI_CPP}" "void Player::ContinueTaxiFlight()" CONTINUE_BEGIN)
string(FIND "${PLAYER_TAXI_CPP}" "GetSession()->SendDoFlight(mountDisplayId, path, startNode);" CONTINUE_END)
if(CONTINUE_BEGIN EQUAL -1 OR CONTINUE_END EQUAL -1 OR CONTINUE_END LESS CONTINUE_BEGIN)
    message(FATAL_ERROR "Unable to locate ContinueTaxiFlight body")
endif()
math(EXPR CONTINUE_LENGTH "${CONTINUE_END} - ${CONTINUE_BEGIN} + 68")
string(SUBSTRING "${PLAYER_TAXI_CPP}" ${CONTINUE_BEGIN} ${CONTINUE_LENGTH} CONTINUE_BODY)
string(FIND "${CONTINUE_BODY}" "ModifyMoney" CONTINUE_DEBIT)
if(NOT CONTINUE_DEBIT EQUAL -1)
    message(FATAL_ERROR "ContinueTaxiFlight must not debit fare")
endif()

message(STATUS "MoP taxi-persistence source checks passed")
